### PR TITLE
Resolve visibility issues for public APIs

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/16dd5fa1a4acbacf9ed599ea73215861

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c8aa1c247bb185e6b73cbfbd0967d8c0

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/364fc4f9f894bcab182c2f86f79eab23

**Comment by jjhursey** [comment]
Matches the pair of PRs #456 and #454 from `master`

**Pull request merged**
