### PR TITLE
v2.1/Fix the test suite with GDS hash component 

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1224

### CODE REVIEW

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
Ready for review?

**Comment by jjhursey** [comment]
Should this go into the v2.2 branch instead? I don't know if we plan on releasing any more in the v2.1 series

**Comment by karasevb** [comment]
Ready to go

**Comment by karasevb** [comment]
@jjhursey this PR fixes test suite issues only and should go to v2.1. for the case if somebody posts a PR to this branch.

**Comment by jjhursey** [comment]
Just to confirm: no changes were needed in the v2.2 branch, right?

**Comment by artpol84** [comment]
I think they are already there

**Pull request merged**
