### PR TITLE
Skip fastpath/dstore for NULL keys

### PR DESCRIPTION
**Pull request by rhc54**
Refs #1375

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/585a34bd9ffe7a4fd1738894e63a3c9d

**Comment by artpol84** [comment]
@rhc54
Can you provide some insights about what was the problem. I kind of see what it could be, but would like to know for sure.

**Comment by artpol84** [comment]
Is it in context of https://github.com/pmix/pmix/pull/1371?

**Comment by rhc54** [comment]
Actually, I referenced the issue where it can be seen (#1375) most easily. It impacts the case where PMIx_Get is used to "pull" all the info for a given rank, which causes an array of pmix_info_t structs to be returned. I haven't tried queries that returned other types of values that might involve a key, so I don't know if the dstore is always truncating returned keys or only doing so for the array case.

**Comment by artpol84** [comment]
Ok, I found that one as well. We will take a look.

**Comment by jjhursey** [comment]
Will need to backport to the v3.x branch (maybe the v2.x branch).

**Comment by rhc54** [comment]
Already in 3.1.4 - needs to be added to v2.2.3

**Pull request merged**
