### PR TITLE
test: Fix pmix_client/job-fence test checks

### PR DESCRIPTION
**Pull request by artpol84**
(cherry picked from commit d81a28d1300000af3a59cef3ca875f38ff281b66)
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/eefd2c4bf53d4e8bcb7bfee209d8a88b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/28110819b1bb13cf2e32e17eef779f8a

**Comment by jjhursey** [comment]
IBM PGI CI should be fixed now. bot:ibm:pgi:retest

**Comment by artpol84** [comment]
@rhc54 @jjhursey the master PR was merged. please consider this PR for merging.

**Pull request merged**
