### PR TITLE
CI Check: master

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1b16753509efc7fd070f548644a9e7fe

**Comment by jjhursey** [comment]
The cross-version script has been fixed in https://github.com/pmix/pmix-tests/pull/7
After doing so we found that there are some cross-version breaks in master. The signature of which can be seen in [this gist](https://gist.github.com/jjhursey/c72bfd57d9f9f39d7d9192407aab8b7e).

**Comment by rhc54** [comment]
@jjhursey I see that the tool test is "passing" for all branches with v1.2, yet v1.2.x does not support tools. Is this just because you are "skipping" that test somehow? Or is this a false positive?

**Comment by jjhursey** [comment]
It looks like a false positive. The simtest is returning `0`, but the output is confusing. There is no `simptool` test in `v1.2` but the `simptest` seems to be ok with running anyway. So any non-v1.2 server testing against v1.2 tool is pointing to a non-existant test, but still running and passing.

I'll update the xversion script to skip testing v1.2 with tools, and add a check that the `simptool` exists before running the test.

It would also be good to go back and fix `simptest` to be more strict about its argument checking. Unfortunately, that means touching all of the branches. It might be worth moving these packaged tests into `pmix-tests` repo.

**Comment by rhc54** [comment]
> It would also be good to go back and fix simptest to be more strict about its argument checking. Unfortunately, that means touching all of the branches. It might be worth moving these packaged tests into pmix-tests repo.

I believe I actually have them there, though they are probably stale and need refreshing. Might also want to put the "make check" tests in there too for similar reasons?

**Comment by rhc54** [comment]
> So any non-v1.2 server testing against v1.2 tool is pointing to a non-existant test, but still running and passing.

Ouch - that sucks. I'll see what I can do.

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cb6695df9b32ee35d1f70773ebc8b023

**Comment by rhc54** [comment]
@jjhursey This is really disturbing. The xversion test reported "all pass" on https://github.com/pmix/pmix/pull/1255. However, after committing that PR (which didn't contain anything that should have impacted xversion), this PR continues to fail xversion with the same signature.

So why did the test report "all pass" on the other PR? I even checked the gist and it showed all good.

**Comment by artpol84** [comment]
@jjhursey
It seems to me that this CI is testing branches the way they are next to each other as opposed to testing a particular PR against them. Is that correct?

**Comment by artpol84** [comment]
My bad, now I see that PRs branch is also in the list

**Comment by artpol84** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fd049c96099aa9d81e93bbb9cd47bd2b

**Comment by artpol84** [comment]
#1260 Has fixed the vast majority of client failures.
I asked @karasevb to have a look into the tools failures as @rhc54 is not able to take it now if I understood him correctly.

**Comment by jjhursey** [comment]
On #1255 the Cross Version CI was triggered before we merged the xversion script fixes. So it passed because it was running the 'old broken' version of the script. Per comment [here](https://gist.github.com/ibm-ompi/ce2ee1a5c3f3edccaa2fddff5a691918#gistcomment-2919965)

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/253c6273a04cad380d46bab4b5ec91e9

**Comment by artpol84** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/22c49f19faf2ee773230e71f4841a5c2

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/511cee2fbddc22ff71f83a8533014815

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
bot:ibm:xvertool:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/99f2542447fcac13b9b67db52f562baa

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e69e2b014d359478dcd061cba913a4ca

**Comment by jjhursey** [comment]
bot:ibm:xver:retest bot:ibm:xvertool:retest

**Comment by jjhursey** [comment]
bot:ibm:xvercheck:retest

**Pull request closed without merging**
