### PR TITLE
Fix python generate_regex function

### PR DESCRIPTION
**Pull request by dsikich**
The python generate regex function was calcuating the
length of the returned regex from PMIx_generate_regex
incorrectly. It was also indexing into regex with the
incorrect values. This was caused by the recent changes
to what is returned by the PMIx_generate_regex function.

Also, code was never entering this block:

```c
if "pmix" == regex[:4]:
```

Even when it should have, so I think the second commit should fix that, where I convert
the byte literal to ascii. 

Signed-off-by: Danielle Sikich (Intel) <danielle.sikich@intel.com>

### CODE REVIEW

**Comment by rhc54** [comment]
I'm afraid this isn't quite correct. The regex consists of a prefix followed by a ':' plus a NULL terminator (to end the string) and then the payload, which can include arbitrary characters (including NULLs) anywhere inside it. The current code assumes that the payload is a NULL-terminated string - it therefore will truncate the payload if that payload includes a NULL byte.

If the regex has a "pmix" prefix, that indicates it is a "native" regex and the payload therefore consists of a NULL-terminated string - i.e., it looks like:
```
pmix:<0><string>
```
You can't just set:
```python
ba = bytearray(regex)
```
because the bytearray function will truncate the regex at the end of the prefix (which is NULL terminated). You need to pull the entire regex (the two concatenated strings) into the bytearray.

If it has a "blob" prefix the regex (and the ppn is just another regex) looks like this:
```
blob:<0>1234<0><bytearray>
```
where `<0>` is a NULL terminator. The "1234" string tells you the length of the enclosed bytearray. You therefore need to set the size of the output bytearray to include the prefix, the size string, and the entire input bytearray.

Finally, there is a third case where this is no prefix at all - i.e., you will not find a ':' in the string. This means that the regex is simply a string and can be directly copied across as a bytearray.

**Comment by dsikich** [comment]
@rhc54 ok, I think what was actually happening was that even if regex[:4] was "pmix" it was in byte form so it was never entering the if statement when it was a "native" regex. So it would go into the else block and parse the regex incorrectly in that case.

**Comment by dsikich** [comment]
@rhc54 Is there still changes I need to make to this PR? I update the length calculations, and I updated the pmix string comparison since even if the byte literal was 'pmix' it was still failing the comparison without the conversion to ascii and never going into the if statement.

**Comment by rhc54** [comment]
Yes - please see my prior note. The parsing of the returned value from "PMIx_generate_regex" is incorrect and needs to be updated.

**Comment by dsikich** [comment]
@rhc54 ok, I pushed an update. Should PMIx_generate_ppn return a regex to the ppn variable? It looks like it is not returning a regex currently.

**Comment by rhc54** [comment]
Both "generate_regex" and "generate_ppn" can return a simple string:

> Finally, there is a third case where this is no prefix at all - i.e., you will not find a ':' in the string. This means that the regex is simply a string and can be directly copied across as a bytearray.

If the regex would be longer than the simple string, then we return the string - and there will be no prefix.

**Pull request merged**
