### PR TITLE
Testing PTL handshake

### PR DESCRIPTION
**Pull request by karasevb**
Do not merge this PR, it is intended for testing PTL handshake scenario under CI.
This PR adds a `psec/simple` component, with a handshake implemented.
The priority of `psec/simple` set higher then other psec components to ensure testing the handshake with `psec/simple` in PTL.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4a43e62a185e00bf4cfefe0fd572ab8a

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/04f922590a4db35e13269cc733d0e91b

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d8e7b71ae4f1557f3c6364ccf23e6513

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f8b3815ff472051b6b58482863b0f427

**Comment by karasevb** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d690f2213b367777ada5d0203f076a11

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/aab756c9de61fabfaef92276016a8301

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d7d6b75133048b764fd28d7b69791442

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0a5a46a08b5efcc9b99206a5712ad9ad

**Comment by jjhursey** [comment]
Note I have split the cross-version CI into two parts
 - `IBM CI (Cross-version)` - for client/server connections. This should pass.
 - `IBM CI (Cross-version: Tool)` - for the tool/server connections. This should fail at the moment.

This PR fails both CI tests indicating that something is broken in the client/server connection handshake that needs to be fixed in this PR.

**Comment by artpol84** [comment]
This PR is out-of-date. We merged https://github.com/pmix/pmix/pull/1277 and I suspect they are conflicting.

Are you interested in enabling dummy/handshake in the CI?

**Comment by karasevb** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/44bb70b6a717409bf5ad80a406e5c891

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/df178257cd24de7818ea0c23038ecc64

**Comment by karasevb** [comment]
PR synced with the master branch.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c64bd42ce8286d62716febccd2e11ba7

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/107d33b3a49728c320a225a4737aa30f

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8198d5030b5e90fb1b0d529b2ccbe769

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1a01800024b598cffa77d36a50c49925

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/24183ee6cb241cd5c7f52675cd6620a5

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/36e11e8f28d6317e94ca54c09b0fb024

**Comment by rhc54** [comment]
@karasevb I believe this can now be closed. We pass all client-based xversion tests. We will have to explore the tools-based tests separately.

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by karasevb** [comment]
@rhc54 Mellanox Jenkins is on maintenance now, I would like to close when Jenkins back and check this PR.

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
bot:ibm:xver:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4b5d9a7102f9914db67e9c5ac158b876

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by karasevb** [comment]
bot:mellanox:retest

**Pull request closed without merging**
