### PR TITLE
Add python wrapper for PMIx_Lookup

### PR DESCRIPTION
**Pull request by dsikich**
@rhc54 Can you check that I am calling PMIx_Lookup correctly? When the pdata returns from PMIx_Lookup I get a "-47", "function not supported" error. 

Signed-off-by: Danielle Sikich (Intel) <danielle.sikich@intel.com>

### CODE REVIEW

**Comment by rhc54** [comment]
You will indeed get "not supported" because the `server.py` program doesn't provide the server module function to implement it. Frankly, you should be getting the same error for the `publish` command as nothing was provided to support it either.

You can see that is the case when looking at the stub functions that provide the interface between the python server and the PMIx server library - e.g., the function behind "publish":
```python
cdef int publish(const pmix_proc_t *proc,
                 const pmix_info_t info[], size_t ninfo,
                 pmix_op_cbfunc_t cbfunc, void *cbdata) with gil:
    keys = pmixservermodule.keys()
    if 'publish' in keys:
        args = {}
        myprocs = []
        ilist = []
        pmix_unload_procs(proc, 1, myprocs)
        args['proc'] = myprocs[0]
        if NULL != info:
            pmix_unload_info(info, ninfo, ilist)
            args['info'] = ilist
        rc = pmixservermodule['publish'](args)
    else:
        return PMIX_ERR_NOT_SUPPORTED
```
Since `server.py` does not provide a "publish" module, this function will always return "not supported" to the client.

That said, your code looks fine - it simply can't yield any other response until `server.py` gets extended.

**Comment by dsikich** [comment]
@rhc54 Ah, ok. Do you want to wait to merge this code until server.py gets extended? Or should I submit this as a regular PR now?

**Comment by rhc54** [comment]
Why don't you add the server.py code to this PR and then remove the "draft" status - we should probably commit them together.

**Comment by dsikich** [comment]
@rhc54 sounds good

**Comment by dsikich** [comment]
@rhc54 I'm in the process of adding the server.py code for lookup and publish so I am closing this one and will open a new PR with this code in it.

**Pull request closed without merging**
