### PR TITLE
PTL: Fix the connection establishment protocol (minimalistic)

### PR DESCRIPTION
**Pull request by artpol84**
Avoid sending extra message in the client connection case.
Is an alternative to:
https://github.com/pmix/pmix/pull/1240

Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54,
this is an alternative (minimalistic) version of #1240 as discussed per telecon 05/16/2019.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/1d2d82316a16127b1adb5d96d85f2931

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/75b0da8609eaaba4c01cef2f0f3bc851

**Comment by artpol84** [comment]
Looks like magically we have everything fixed!
I think that extra message was the root cause!

**Comment by artpol84** [comment]
The PR doesn't break cross-version further with respect to tools, though. 
This was the goal!

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/94d6f3a106dc55d17920e793f4132684

**Comment by jjhursey** [comment]
CI xversion checker mis-flagged this failure line:
```
Run ***FAILED***: v2.0 -> cli_connect_v2
```
Since `cli_connect_v2` is pointed at `master` it shouldn't be tested against `v2.0` that way (v2.0 server against a master PR client). I'll see if I can engineer some way to address that.

**Comment by artpol84** [comment]
I think this one is ready for the review.
I ran it through the many make-check iterations test and it also uncovers no issues.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5b59ca4a5d0d574032c6a44e97c470fc

**Comment by artpol84** [comment]
@rhc54, do you have any concerns about this variant?

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/3595e7df08a17f13f77812f84a5d6fd1

**Comment by artpol84** [comment]
#1273 introduces a simple psec/handshake plugin to test this codepath.
It demonstrates that this codepath is broken as described in https://github.com/pmix/pmix/pull/1240#issuecomment-491475003.

#1274 demonstrates that this PR is fixing this issue.

@karasevb will PR this psec component as a stand-alone PR. It will be disabled by default and will require./configure option to enable it for CIs for example.

In conjunction with xversion results I think that this PR is addressing all concerns raised in #1240 and is ready to go.

**Comment by artpol84** [comment]
@rhc54 can we proceed with this?

**Comment by rhc54** [comment]
Sorry for delay - as I've said elsewhere, I will take a look at this as soon as I finish prepping day 1 of the tutorial I have to give in a couple of weeks. Hopefully tomorrow.

**Comment by artpol84** [comment]
Thank you.

**Comment by rhc54** [comment]
Sorry for the delay. I have only one question. In ptl_tcp_component.c:1758-1759, you convert the reply using `htonl` and send the result to the connecting tool. However, it is received in ptl_tcp.c:1320-1321 and not converted back using `ntohl` before testing the value. Was that an oversight?

Just wondering how the handshake test passed given the mismatch.

**Comment by artpol84** [comment]
Good question.
* The value sent in [ptl_tcp_component.c:1750-1751](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp_component.c#L1750:L1751)  (or [ptl_tcp_component.c:1909](https://github.com/pmix/pmix/pull/1264/files#diff-32de0a96107c764da3520d9fd49be18bR1909) in this fix) is being received in [ptl_tcp.c:1241](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1241) and converted in [ptl_tcp.c:1251](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1251) so all is good here.
* Now the receive in [ptl_tcp.c:1320-1321](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1320:L1321) is indeed missing conversion. I think the problem there is that IBM tests were broken and haven't run, so we don't actually have tools part for that:
```
4 successful checks
@ompiteam-bot Commit email checker — All commits have good email addresses. Yay! Required
@mellanox-github Mellanox — Build finished. Details
@ompiteam-bot Signed-off-by checker — All commits signed off. Yay! Required
continuous-integration/travis-ci/pr — The Travis CI build passed Details
```
As you can see only travis and Mellanox CIs ran for this PR. I'll retest it now and we will see if it will be captured.

I think you that you spot the issue there and we need to fix it as well. I'll push the fix for that.

**Comment by rhc54** [comment]
Yes, IBM is down and Josh is on vacation thru the holiday. I'm okay with this as-is. Thanks for the fix!

**Pull request merged**
