### PR TITLE
Jenkins test

### PR DESCRIPTION
**Pull request by karasevb**
Don't merge. Jenkins test only.

### CODE REVIEW

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
bot:retest

**Comment by rhc54** [comment]
@karasevb @artpol84 Hey guys - will you be fixing the Jenkins server over here? Thanks for fixing the OMPI one - I suspect it's the same fix required here?

**Comment by artpol84** [comment]
I guess that fix was universal. I triggered retest on another commit. We will see if something is still needed to be done.

**Comment by karasevb** [comment]
Closed.

**Pull request closed without merging**
