### PR TITLE
Add missing file to tarball and missing attributes

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/33f77554f5c47055e07cb54b75ef7d60

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/31b818e4990002fd2904293dd227d681

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5dc4ac4919a6eb588adde22325820114

**Comment by rhc54** [comment]
bot:mellanox:retest

**Pull request merged**
