### PR TITLE
Port the compression framework to PMIx

### PR DESCRIPTION
**Pull request by rhc54**
Bring over the OPAL compress framework and move the zlib support into it
as another component. For now, let the bzip and gzip components continue
to only work on files even though we don't need that right now (we may
want it later).

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c1643cc1cc4dac9977f532bd17522dd6

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/15b817eb8272f7f4146448b7e61b97af

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/497da04a145da0bbd2133a95f312db21

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dcbcc910ce02931f46f0a257018f343f

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b2e7bbf7ccc08451402f058d3f23540b

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/db3c8512ca4cddc3fc7ee164fbb172b3

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/75d202a5ba2c9a0fa43b3cf51d46f71a

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/abb5176b33744a49aa15310d41d3cde8

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d4a4e5f2190725b709a61688b3143904

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/529667a035bfa89f4e87ea29fcc2f38c

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/78d69f8da1400a123dcec0fd0a0e7e10

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7d5e9d3e7181630fbaadf96f2718b32a

**Comment by rhc54** [comment]
weird - the IBM tests are report clock skew errors! Try it again

bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/947e48a8d197d60976b9635ff1cade9c

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/206300b30adabb687da194b40280cc11

**Pull request closed without merging**
