### PR TITLE
Fix memory leak in _attach_new_segment

### PR DESCRIPTION
**Pull request by footpatch**

### CODE REVIEW

**Comment by rhc54** [comment]
@footpatch Thanks for the patch! Would you mind signing it off:
```
Signed-off-by: Name <email>
```
Thanks again!

**Comment by footpatch** [comment]
Signed-off-by: Rijnard van Tonder voetpatch@gmail.com

**Comment by rhc54** [comment]
My apologies, I should have been clearer - we actually need that sign-off in the commit message. You can do that by:
```
$ git commit --amend --signoff
```
and then push it to your branch.

**Comment by rhc54** [comment]
Perfect - thanks!

**Pull request merged**
