### PR TITLE
Testing PTL handshake with PR#1264

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1273, but includes #1264.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/28a76dde3be49a391ce75b80a5845f45

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4c8eb8678cb8c0b212adbc35189981fb

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/db66900f01b59dc802309c622faacfe0

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/30de66828aa125ecd01678fee76cd57b

**Comment by karasevb** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:ibm:retest

**Comment by artpol84** [comment]
@jjhursey it seems like IBM CI is not picking up

**Comment by artpol84** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/49071230df89b98dd122c0672b9141a6

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c89f2b011e393334f4b9bf71590eab84

**Comment by artpol84** [comment]
@jjhursey 
Note that in "Cross-version" you are still running tools:
```
============================== Summary (Client) ==============================
Run PASS: master -> master
Run PASS: master -> v3.1
Run PASS: master -> v3.0
Run PASS: master -> v2.2
Run PASS: master -> v2.1
Run PASS: master -> v2.0
Run PASS: master -> v1.2
Run PASS: master -> simple_with_PR1264
Run PASS: v3.1 -> master
Run PASS: v3.1 -> v3.1
Run PASS: v3.1 -> v3.0
Run PASS: v3.1 -> v2.2
Run PASS: v3.1 -> v2.1
Run PASS: v3.1 -> v2.0
Run PASS: v3.1 -> v1.2
Run PASS: v3.1 -> simple_with_PR1264
Run PASS: v3.0 -> master
Run PASS: v3.0 -> v3.1
Run PASS: v3.0 -> v3.0
Run PASS: v3.0 -> v2.2
Run PASS: v3.0 -> v2.1
Run PASS: v3.0 -> v2.0
Run PASS: v3.0 -> v1.2
Run PASS: v3.0 -> simple_with_PR1264
Run PASS: v2.2 -> master
Run PASS: v2.2 -> v3.1
Run PASS: v2.2 -> v3.0
Run PASS: v2.2 -> v2.2
Run PASS: v2.2 -> v2.1
Run PASS: v2.2 -> v2.0
Run PASS: v2.2 -> v1.2
Run PASS: v2.2 -> simple_with_PR1264
Run PASS: v2.1 -> master
Run PASS: v2.1 -> v3.1
Run PASS: v2.1 -> v3.0
Run PASS: v2.1 -> v2.2
Run PASS: v2.1 -> v2.1
Run PASS: v2.1 -> v2.0
Run PASS: v2.1 -> v1.2
Run PASS: v2.1 -> simple_with_PR1264
Run PASS: v2.0 -> v2.0
Run PASS: v1.2 -> v1.2
Run ***FAILED***: simple_with_PR1264 -> master
Run PASS: simple_with_PR1264 -> v3.1
Run PASS: simple_with_PR1264 -> v3.0
Run PASS: simple_with_PR1264 -> v2.2
Run PASS: simple_with_PR1264 -> v2.1
Run PASS: simple_with_PR1264 -> v2.0
Run PASS: simple_with_PR1264 -> v1.2
Run PASS: simple_with_PR1264 -> simple_with_PR1264
============================== Summary (Tool) ==============================
Run PASS: master -> master (Tool)
Run PASS: master -> v3.1 (Tool)
Run PASS: master -> v3.0 (Tool)
Run PASS: master -> v2.2 (Tool)
Run PASS: master -> v2.1 (Tool)
Run PASS: master -> v2.0 (Tool)
Run PASS: master -> simple_with_PR1264 (Tool)
Run PASS: v3.1 -> master (Tool)
Run PASS: v3.1 -> v3.1 (Tool)
Run PASS: v3.1 -> v3.0 (Tool)
Run PASS: v3.1 -> v2.2 (Tool)
Run PASS: v3.1 -> v2.1 (Tool)
Run PASS: v3.1 -> v2.0 (Tool)
Run PASS: v3.1 -> simple_with_PR1264 (Tool)
Run ***FAILED***: v3.0 -> master (Tool)
Run ***FAILED***: v3.0 -> v3.1 (Tool)
Run PASS: v3.0 -> v3.0 (Tool)
Run ***FAILED***: v3.0 -> v2.2 (Tool)
Run PASS: v3.0 -> v2.1 (Tool)
Run PASS: v3.0 -> v2.0 (Tool)
Run ***FAILED***: v3.0 -> simple_with_PR1264 (Tool)
Run ***FAILED***: v2.2 -> master (Tool)
Run ***FAILED***: v2.2 -> v3.1 (Tool)
Run PASS: v2.2 -> v3.0 (Tool)
Run ***FAILED***: v2.2 -> v2.2 (Tool)
Run PASS: v2.2 -> v2.1 (Tool)
Run PASS: v2.2 -> v2.0 (Tool)
Run ***FAILED***: v2.2 -> simple_with_PR1264 (Tool)
Run ***FAILED***: v2.1 -> master (Tool)
Run ***FAILED***: v2.1 -> v3.1 (Tool)
Run PASS: v2.1 -> v3.0 (Tool)
Run ***FAILED***: v2.1 -> v2.2 (Tool)
Run PASS: v2.1 -> v2.1 (Tool)
Run PASS: v2.1 -> v2.0 (Tool)
Run ***FAILED***: v2.1 -> simple_with_PR1264 (Tool)
Run PASS: v2.0 -> v2.0 (Tool)
Run ***FAILED***: simple_with_PR1264 -> master (Tool)
Run PASS: simple_with_PR1264 -> v3.1 (Tool)
Run PASS: simple_with_PR1264 -> v3.0 (Tool)
Run PASS: simple_with_PR1264 -> v2.2 (Tool)
Run PASS: simple_with_PR1264 -> v2.1 (Tool)
Run PASS: simple_with_PR1264 -> v2.0 (Tool)
Run PASS: simple_with_PR1264 -> simple_with_PR1264 (Tool)
```

**Comment by jjhursey** [comment]
That test was run 4 days ago, so isn't the new iteration (which I activated yesterday). I'll rerun the new iteration.
bot:ibm:xver:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8e7504ca57835387935cb6e6aa2d119a

**Comment by rhc54** [comment]
@karasevb Same here - I believe this should now be closed

**Comment by karasevb** [comment]
bot:mellanox:retest

**Pull request closed without merging**
