### PR TITLE
OpenMP/MPI Coordination

### PR DESCRIPTION
**Pull request by rhc54**
Add some coordination attributes and status codes

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9c68f77d098f5cb4bbfd6c9fdfbd1e76

**Comment by jjhursey** [comment]
IBM PGI CI should be fixed now. bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/119eddcce790f4c68c6d65b11f586ea7

**Comment by rhc54** [comment]
bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Pull request merged**
