### PR TITLE
Per recommendation from @angainor, add missing directory to rpm.

### LINKED ISSUE #500: rpmbuild --rebuild fails
Sorry, if that is naive/redundant - I'm not a RedHat expert, and I haven't found any posts describing this problem with PMIx. I can't build RPMs on CentOS Linux release 7.3.1611 (Core):

`rpmbuild --rebuild pmix-2.0.1-1.src.rpm`
`[...]`
`File not found: /nird/home/marcink/rpmbuild/BUILDROOT/pmix-2.0.1-1.x86_64/etc`

Adding creation of /etc to the spec file helped, i.e., the RPMs have been created:

`   %{__make} install DESTDIR=$RPM_BUILD_ROOT %{?mflags_install}`
`+ %{__mkdir_p} $RPM_BUILD_ROOT/etc`

The same happens for an earlier 1.2.3 version. Do I do sth wrong, or is this a bug?

Thanks!

Marcin Krotkiewski

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to @angainor for reporting the problem and recommending the fix.

Fixes #500

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/aa3dd06517c7d36c950b07b3cdab2faf

**Comment by rhc54** [comment]
Now that's a new one! @jjhursey The log saids everything passed, the green check mark was given - so why the "failed" comment?

**Comment by jjhursey** [comment]
@rhc54 Cranky CI. A poorly timed network event right at the end caused it to trip the comment post, but after it already said success. I wish Jenkins gave us the flexibility to handle that type of situation. Disregard the comment, the test passed. Sorry for the noise.

**Comment by rhc54** [comment]
no problem - thanks for the explanation!

**Comment by angainor** [comment]
Unfortunately, not quite there:

RPM build errors:
    File not found by glob: /nird/home/marcink/rpmbuild/BUILDROOT/pmix-2.1.0-1.x86_64/usr/bin/*
    File not found: /nird/home/marcink/rpmbuild/BUILDROOT/pmix-2.1.0-1.x86_64/etc

Problem 1: /usr/bin directory is not created / needed by pmix, so adding it in %files section causes an error. It is needed for openmpi, that's why it was included in the original spec file, I assume.

Problem 2: /etc is not created / needed by pmix, which was the original problem. It seems it is still used here in the %files section, hence build fails.

Solution (?): remove %{_bindir}/* from the spec file, and remove stuff related to _sysconfdir:

%if !%{sysconfdir_in_prefix}
%{_sysconfdir}
%endif

Otherwise, those directories should be populated by pmix build. I also suspect that /etc should be included in a similar fashion to the others, i.e., 

%{_sysconfdir}/*

**Comment by rhc54** [comment]
Rats - we will need those directories eventually, but I will comment them out for now.

Just for my info: what system are you building these on? I'm on CentOS-7, and I'm not getting any errors or warnings on the build or even the rebuild

**Comment by rhc54** [comment]
@angainor @abouteiller Please see if this now works for you

**Comment by angainor** [comment]
I'm running rpmbuild --rebuild on CentOS Linux release 7.3.1611.

If you will need those, why not include some conditionals in the %files section based on whether %{_bindir} and %{_sysconfdir} exist in RPM_BUILD_ROOT.

**Comment by rhc54** [comment]
I can refine it later, once we know that this now works. Interesting that we are getting quite different results even though we are running rebuild on the same OS.

**Comment by angainor** [comment]
This version worked fine \o/
Strange indeed. different rpm? 
$ rpmbuild --version
RPM version 4.11.3

**Comment by rhc54** [comment]
Thanks for checking. I'll go with this for now.

No, we are using the same version:
```
$ rpmbuild --version
RPM version 4.11.3
```
shrug - no idea.

**Pull request merged**
