### PR TITLE
v3.0/server: Fix PMIx_Server_Finalize hang

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1246

### CODE REVIEW

**Comment by karasevb** [comment]
Note: Mellanox Jenkins will be happy for this branch once #1226 is merged.

**Comment by artpol84** [comment]
@karasevb I assume we are waiting for #1226 to be merged for the Mellanox Jenkins to pass, right?

**Comment by artpol84** [comment]
ok, sorry I missed the previous comment.

**Comment by rhc54** [comment]
bot:mellanox:retest

**Pull request merged**
