### PR TITLE
Support singleton operations under PMI-1 and PMI-2

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>
(cherry picked from commit d52fb9d738665db4fc2bae079b5ec6dc2bca66c3)

### CODE REVIEW

**Comment by rhc54** [comment]
@koomie - this is the v1.2.4 version

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/788fd18d9441b373b40f47ffa60fbf86

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/cb9521937e7717e7556682be0a2a7c58

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/addb204e82acdc24204e26b675665d29

**Comment by koomie** [comment]
Thanks for the patch. I have applied and now see a different message running a hello world with mpich configured against (patched) pmix 1.2.3.  Logging the different output below:

Here is the **before**:

```
[ohpc-test@sms007 ~]$ mpicc hello.c
[ohpc-test@sms007 ~]$ ./a.out 
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474): 
MPID_Init(152).......: channel initialization failed
MPID_Init(408).......: PMI_Init returned 1
```

And here is the **after** with patch applied:

```
[ohpc-test@sms007 ~]$ ./a.out 
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474): 
MPID_Init(152).......: channel initialization failed
MPID_Init(464).......: Out of memory (unable to allocate -713412383 bytes)
```

**Comment by rhc54** [comment]
Can you tell me how you configured/build mpich? I want to ensure I'm doing it the same way

**Comment by koomie** [comment]
You bet; hopefully I'm not screwing up. I've been leveraging the configure options that would normally be used to tell mpich to point to the PMI libs in slurm, but giving paths to my separate pmix build.

```
ohpc-test@sms007 ~]$ mpichversion 
MPICH Version:    	3.2
MPICH Release date:	Wed Nov 11 22:06:48 CST 2015
MPICH Device:    	ch3:nemesis
MPICH configure: 	--prefix=/opt/ohpc/pub/mpi/mpich-gnu7-ohpc/3.2 CFLAGS=-I/opt/ohpc/admin/pmix/1.2.3/include LIBS=-L/opt/ohpc/admin/pmix/1.2.3/lib -lpmix --with-pm=none --with-pmi=slurm
```

Since the mpich autconf setup is expecting to find the pmi headers in `slurm/pmi.h`, I had to create one small patch for mpich's configure script to remove the slurm prefix.  That patch is here:

https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.3_Factory/components/mpi-families/mpich/SOURCES/config.pmix.patch

The patched pmix RPM I just built (for centos) is at: http://build.openhpc.community/OpenHPC:/1.3:/Update3:/Factory/CentOS_7/x86_64/pmix-ohpc-1.2.3-7.1.x86_64.rpm

The one tweak to the pmix packaging is that I soft link `libpmi.so` to `libpmix.so` so that autoconf checks expecting to find functions in libpmi work out of the box.

If you want to see the exact spec file it's at: https://build.openhpc.community/package/show/OpenHPC:1.3:Update3:Factory/pmix

**Comment by rhc54** [comment]
Okay, I can replicate - I'll work on it!

**Comment by koomie** [comment]
Thanks. fwiw, I double checked that if I have mpich link against the libpmi.so provided from a slurm build, the singleton outside of the resource manager does run ok.

**Comment by rhc54** [comment]
@koomie I updated this PR so that we install libpmi and libpmi2 when configured for backward compatibility - means you no longer have to manually create the symlinks for packages that are hardcoded to those library names

**Comment by rhc54** [comment]
@jjhursey This capability is needed for complete PMI-1 and PMI-2 compatibility to support singletons.

**Pull request merged**
