### PR TITLE
Don't try to add data to dstore that doesn't exist to avoid warning/e…

### PR DESCRIPTION
**Pull request by dsolt**
…rror messages being logged.

### CODE REVIEW

**Comment by rhc54** [comment]
@dsolt Just curious - why would we receive a zero-byte payload for a proc's job-level info?

**Comment by dsolt** [comment]
I think it happens every time the ranks are split across more than 1 host.   Unless I'm not calling PMIx_Register_nspace correctly?   When I call PMIx_Register_nspace, I only pass down proc level details for the ranks that are local to that host, but then dstore seems to cycle through all ranks in the namespace looking for proc data to push into the dstore

**Comment by rhc54** [comment]
Hmmm...well, that's the issue. We were expecting you to pass down all info for all ranks, but it is also true that we don't need all the details. ORTE currently passes down the local rank, node rank, and node ID for every rank - and that's it. We actually _do_ require that much info for every rank in order for them to auto-wireup.

Are you at least passing that much? If not, then that's a problem.

**Comment by rhc54** [comment]
@dsolt I'm going to close this one as it seems that the problem here is the lack of data required by the PMIx spec. Instead, I've provided a suppressible warning of the situation - please see https://github.com/pmix/pmix/pull/376

**Pull request closed without merging**
