### PR TITLE
pmix_perf: Use knowledge of the dstore internals to get it's size

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
This PR adds additional line in the pmix_perf output that provides the amount of memory occupated by dstore as per internal dstore structure inspection (should be very precise):

```
init: 0.027065; put: 0.000049; commit: 0.001737; fence: 0.002969; get: 0.000394; total: 0.036718
init:          max 0.032055 min 0.022076
put:           loc 0.000049 rem --------
get:           loc 0.000020 rem -------- all 0.000020
get:           min loc 0.000018 rem -nan (loc: 0, rem: 0)
get:           max loc 0.000022 rem -nan (loc: 1, rem: 0)
total:         max 0.042217 min 0.031219
mem:           loc 920.00 avg 918.00 min 916.00 max 920.00 total 1836.00 Kb
shmem:         job_info: 9.77 total 15.10 Kb   <----
```

Measurements performed 2 times:
* after PMIx_Init and access to the job information. This provides information about total job level info size
* After all exchanges are finished, this contains additional size added by key-values submitted by application.

**Comment by artpol84** [comment]
I checked that I've signed off my commits, so I think it is safe to merge.

**Comment by artpol84** [comment]
@rhc54 @jjhursey can you check what is wrong with the sign-off checker? I don't know how to retrigger it.

**Comment by artpol84** [comment]
bot:retest

**Comment by rhc54** [comment]
It occasionally hangs due to a timing issue. All you can do to retrigger it is change something and push. If the master has changed, you could do it by rebasing and then force pushing.

**Pull request merged**
