### PR TITLE
v1.2 Fixed faulty compares in PMI/PMI2 tests

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>
(cherry picked from commit 4118eed8a9acaa6948e0069fb65fb411ffa3d94f)

Conflicts:
	test/pmi2_client.c
	test/pmi_client.c

### CODE REVIEW

**Comment by jsquyres** [comment]
@karasevb @artpol84 @rhc54 This PR looks like it could be a bug on github: all the CI tests have passed, but GH still says "Required statuses must pass before merging".  Please don't merge or change this PR -- I want to submit this PR to github as a possible bug (you might want to submit this patch in a new PR and merge it from there).

**Comment by jsquyres** [comment]
Posted in https://github.community/t5/How-to-use-Git-and-GitHub/PR-says-quot-Required-statuses-must-pass-before-merging-quot-but/m-p/4919#M1583.

**Comment by artpol84** [comment]
@jsquyres any news

**Comment by rhc54** [comment]
Github was unable to figure out the issue and could only suggest simply reposting the PR. Given that the v1.2 series has been retired, there isn't much point in doing so - I would suggest just closing it.

**Comment by jsquyres** [comment]
@rhc54 Apparently we contacted the github community, and they couldn't help us.  I filed a ticket yesterday, and apparently github now fixed the issue.

...but as you point out, this is for the v1.2 series and is moot... you guys can determine what you want to do with this PR.

**Pull request closed without merging**
