### PR TITLE
Warning: Unused Parameters

### PR DESCRIPTION
**Pull request by ax3l**
Silence a selection of unused parameters (`-Wunused-parameter`).

### CODE REVIEW

**Comment by rhc54** [comment]
I think what you did with the atomic and the mca/base files is fine. I prefer the solution I used for the bfrops files over these as I think there is some value to having a more directed check of those params. Thus, I'd suggest removing the bfrops changes here and just pushing the rest.

**Comment by ax3l** [comment]
Thank you for the update, looks good to me!

**Comment by rhc54** [comment]
Kewl - I'll commit once it passes CI. Probably best to do this in pieces as master can be a moving target 😄

**Comment by ax3l** [comment]
Uh-oh, we have to fix some tests now :D

**Comment by rhc54** [comment]
No, hold on - there is another PR that is addressing those failures. They are unrelated to this one.

**Comment by ax3l** [comment]
ok, just ping me when it's merged and I will rebase this PR

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/92a4579ca8e4e433e6b61c25f92693e7

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/89d947d2ced08a15b639a1cae8eab266

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e893861c59391070fc81162d212e83ec

**Comment by ax3l** [comment]
@rhc54 can you please take a look at your diff again? The tests still pass (besides integration to some branches?) with my updates but adding your two commits as well causes some of them to fail at runtime, probably because the previously unused arguments are now checked properly. I can reproduce the failing tests locally as well.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/09c719521ec3ea09e3cc2214de228075

**Comment by rhc54** [comment]
Done! We redirect some of the declared types to generic routines - needed to update the type check accordingly.

**Comment by ax3l** [comment]
Thanks, that fixed it! :)

**Pull request merged**
