### PR TITLE
Fix the tests in the "test" subdir and silence a warning

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
Fixes #1204

**Comment by rhc54** [comment]
Fixes #1198

**Comment by artpol84** [comment]
@rhc54 thank you very much for tracking this down.
I am sorry for being silent - I was on vacation past 2 weeks.
A couple of follow-up questions:
* Have you had a chance to identify the difference between CI and `make check`? 
  * In particular why 
https://github.com/pmix/pmix/pull/1207/files#diff-45e5beb2251b9d715cf51150bb055a1fR155
 wasn't triggered in CI and did trigger in `make check`?
  * The fact that we were not tracking `PMIX_ERR_PROC_ENTRY_NOT_FOUND` probably points out that we are not testing `hash` with our CI. I thought we do.
* Does it makes sense to change dstore to return `PMIX_ERR_PROC_ENTRY_NOT_FOUND` in the appropriate places to keep all GDS consistent?

**Comment by rhc54** [comment]
@artpol84 No problem - figured you were probably out 😄 I think the problem is that CI is looking at the exit code of the server, and I found that the server wasn't returning an error on one of the PMIx_Get variations. I was seeing PMIX_ERROR_LOG reports being output, which caught my attention and led me to find that return code mistake. When I changed that, I uncovered the need to update the test.

I only found the `hash` issue by setting `PMIX_MCA_gds=hash` in the environment. Otherwise, the `hash` component is only used to stage the job info and isn't involved in retrieving it. Testing that component on its own is something we probably should add as a separate test case, using one of the tests that failed before.

If it isn't too much effort, it probably does make sense to ensure the `hash` and `dstore` components return consistent values. Might be worth reviewing the `hash` as well as it may not be consistent itself.

Running `make check` in Jenkins would make sense to me, but adding a test to `make check` takes more effort than adding one to Jenkins. I didn't have time to cleanup the `make check` logic - I'm sure someone could do so and make that process more efficient as well. If that gets done, then the two methods for adding a test would be pretty equivalent and just using `make check` would seem reasonable.

**Comment by artpol84** [comment]
I noticed that pmix_test has a parameter to select GDS component:
```
$ ./pmix_test -h
usage: pmix_test [-h] [-e foo] [-b] [-c] [-nb]
	-n       provides information about the job size (for checking purposes)
	-e foo   use foo as test client
	-v       verbose output
	-t <>    set timeout
	-o out   redirect clients logs to file out.<rank>
...
	--gds <external gds name>           set GDS module "--gds hash|ds12", default is hash
```

But I don't see it being used in jenkins scripts. We need to update them. @karasevb please take care of that

**Pull request merged**
