### PR TITLE
preg: fix and enhanced test

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by jjhursey** [comment]
@ggouaillardet Thanks for porting that over!
@rhc54 Do you see any issue in getting this bug fix into the v2.1 and v2.0 series?

**Comment by rhc54** [comment]
Should be okay - doesn't break compatibility and is small.

**Comment by jjhursey** [comment]
Ok. I'll try to get that done today so we can include it in the next rc's

**Comment by jjhursey** [comment]
I filed PR #658 (v2.1) and #659 (v2.0) for this PR.

**Pull request merged**
