### PR TITLE
Update atomics

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ea05cf70710243e871a96ae6114918eb

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/da714c4e689eab9bc0bc4b7605574092

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7362065b0d1fe5339fee3e70d863cc66

**Comment by jjhursey** [comment]
Ref: https://github.com/open-mpi/ompi/pull/4003 which removes the generated asm version of the atomics (which were never well maintained anyway).

**Pull request merged**
