### PR TITLE
Check for EINVAL return from posix_fallocate

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
@alarcher Can you verify this is fixed here as well?

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d8b14ea0727fdeaaab25c628d6c01cc5

**Comment by jjhursey** [comment]
The IBM CI was having some network issues. These network issues are not being displayed in the logs due to an issue in the xversion.py tester script running in quiet mode. I updated the script so it should (1) show the build errors if/when they occur and (2) if a 'git' operation times out because of a network issue then it will try to continue on with what it has to test with if possible. Hopefully, that helps make it a bit more robust.

bot:ibm:retest

**Comment by rhc54** [comment]
@artpol84 I think this is a pretty simple review - the bug reporter has already confirmed it solved the problem on zfs. Would you have a few minutes to take a peek so we can get 3.1.4 out?

**Comment by alarcher** [comment]
@rhc54 Sorry I missed the second message. This works fine. Thank you.

**Pull request merged**
