### PR TITLE
Fix/test crosver

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/614f45ab24f2ffcf1c31e47d777792e6

**Comment by rhc54** [comment]
Already tried that - it doesn't impact the xversion problem

**Comment by artpol84** [comment]
@rhc54
This fixes cross version:
Run ***FAILED***: test_crosver -> master (Tool)
Run PASS: test_crosver -> v3.1 (Tool)
Run PASS: test_crosver -> v3.0 (Tool)
Run PASS: test_crosver -> v2.2 (Tool)
Run PASS: test_crosver -> v2.1 (Tool)
Run PASS: test_crosver -> v2.0 (Tool)
Run PASS: test_crosver -> v1.2 (Tool)
Run PASS: test_crosver -> test_crosver (Tool)

**Comment by artpol84** [comment]
============================== Summary (Client) ==============================
Run PASS: master -> master
Run ***FAILED***: master -> v3.1
Run ***FAILED***: master -> v3.0
Run ***FAILED***: master -> v2.2
Run ***FAILED***: master -> v2.1
Run ***FAILED***: master -> v2.0
Run ***FAILED***: master -> v1.2
Run ***FAILED***: master -> test_crosver
Run ***FAILED***: v3.1 -> master
Run PASS: v3.1 -> v3.1
Run PASS: v3.1 -> v3.0
Run PASS: v3.1 -> v2.2
Run PASS: v3.1 -> v2.1
Run PASS: v3.1 -> v2.0
Run PASS: v3.1 -> v1.2
Run PASS: v3.1 -> test_crosver
Run ***FAILED***: v3.0 -> master
Run PASS: v3.0 -> v3.1
Run PASS: v3.0 -> v3.0
Run PASS: v3.0 -> v2.2
Run PASS: v3.0 -> v2.1
Run PASS: v3.0 -> v2.0
Run PASS: v3.0 -> v1.2
Run PASS: v3.0 -> test_crosver
Run ***FAILED***: v2.2 -> master
Run PASS: v2.2 -> v3.1
Run PASS: v2.2 -> v3.0
Run PASS: v2.2 -> v2.2
Run PASS: v2.2 -> v2.1
Run PASS: v2.2 -> v2.0
Run PASS: v2.2 -> v1.2
Run PASS: v2.2 -> test_crosver
Run ***FAILED***: v2.1 -> master
Run PASS: v2.1 -> v3.1
Run PASS: v2.1 -> v3.0
Run PASS: v2.1 -> v2.2
Run PASS: v2.1 -> v2.1
Run PASS: v2.1 -> v2.0
Run PASS: v2.1 -> v1.2
Run PASS: v2.1 -> test_crosver
Run PASS: v2.0 -> v2.0
Run ***FAILED***: v2.0 -> test_crosver
Run PASS: v1.2 -> v1.2
Run PASS: v1.2 -> test_crosver
Run ***FAILED***: test_crosver -> master
Run PASS: test_crosver -> v3.1
Run PASS: test_crosver -> v3.0
Run PASS: test_crosver -> v2.2
Run PASS: test_crosver -> v2.1
Run PASS: test_crosver -> v2.0
Run PASS: test_crosver -> v1.2
Run PASS: test_crosver -> test_crosver
============================== Summary (Tool) =========================

**Comment by artpol84** [comment]
Not all of it, but the most of it, compared to the master.

**Comment by rhc54** [comment]
All I see are "failed" in the exact same places as before. I'll take a look at it in a bit, but I don't think this is the root cause.

**Comment by artpol84** [comment]
Compare “master” results with “test_crossover”

**Comment by artpol84** [comment]
Test crossover is this branch while master is current master that is broken

**Comment by artpol84** [comment]
**this is a root cause **
It’s not clear to me why this is the problem to realize that

**Comment by rhc54** [comment]
Because I misread your posting of results - the two seemed at odds to each other. The results also do see different from what I obtained earlier, partly because you have snipped the results to ignore some of the failures (my branch was called "fix"):
```shell
============================== Summary (Client) ==============================
Run PASS: master -> master
Run ***FAILED***: master -> v3.1
Run ***FAILED***: master -> v3.0
Run ***FAILED***: master -> v2.2
Run ***FAILED***: master -> v2.1
Run ***FAILED***: master -> v2.0
Run ***FAILED***: master -> v1.2
Run ***FAILED***: master -> fix
Run ***FAILED***: v3.1 -> master
Run PASS: v3.1 -> v3.1
Run PASS: v3.1 -> v3.0
Run PASS: v3.1 -> v2.2
Run PASS: v3.1 -> v2.1
Run PASS: v3.1 -> v2.0
Run PASS: v3.1 -> v1.2
Run PASS: v3.1 -> fix
Run ***FAILED***: v3.0 -> master
Run PASS: v3.0 -> v3.1
Run PASS: v3.0 -> v3.0
Run PASS: v3.0 -> v2.2
Run PASS: v3.0 -> v2.1
Run PASS: v3.0 -> v2.0
Run PASS: v3.0 -> v1.2
Run PASS: v3.0 -> fix
Run ***FAILED***: v2.2 -> master
Run PASS: v2.2 -> v3.1
Run PASS: v2.2 -> v3.0
Run PASS: v2.2 -> v2.2
Run PASS: v2.2 -> v2.1
Run PASS: v2.2 -> v2.0
Run PASS: v2.2 -> v1.2
Run PASS: v2.2 -> fix
Run ***FAILED***: v2.1 -> master
Run PASS: v2.1 -> v3.1
Run PASS: v2.1 -> v3.0
Run PASS: v2.1 -> v2.2
Run PASS: v2.1 -> v2.1
Run PASS: v2.1 -> v2.0
Run PASS: v2.1 -> v1.2
Run PASS: v2.1 -> fix
Run PASS: v2.0 -> v2.0
Run ***FAILED***: v2.0 -> fix
Run PASS: v1.2 -> v1.2
Run PASS: v1.2 -> fix
Run ***FAILED***: fix -> master
Run PASS: fix -> v3.1
Run PASS: fix -> v3.0
Run PASS: fix -> v2.2
Run PASS: fix -> v2.1
Run PASS: fix -> v2.0
Run PASS: fix -> v1.2
Run PASS: fix -> fix
============================== Summary (Tool) ==============================
Run PASS: master -> master (Tool)
Run ***FAILED***: master -> v3.1 (Tool)
Run ***FAILED***: master -> v3.0 (Tool)
Run ***FAILED***: master -> v2.2 (Tool)
Run ***FAILED***: master -> v2.1 (Tool)
Run ***FAILED***: master -> v2.0 (Tool)
Run PASS: master -> v1.2 (Tool)
Run ***FAILED***: master -> fix (Tool)
Run ***FAILED***: v3.1 -> master (Tool)
Run PASS: v3.1 -> v3.1 (Tool)
Run PASS: v3.1 -> v3.0 (Tool)
Run PASS: v3.1 -> v2.2 (Tool)
Run PASS: v3.1 -> v2.1 (Tool)
Run PASS: v3.1 -> v2.0 (Tool)
Run PASS: v3.1 -> v1.2 (Tool)
Run PASS: v3.1 -> fix (Tool)
Run ***FAILED***: v3.0 -> master (Tool)
Run PASS: v3.0 -> v3.1 (Tool)
Run PASS: v3.0 -> v3.0 (Tool)
Run ***FAILED***: v3.0 -> v2.2 (Tool)
Run PASS: v3.0 -> v2.1 (Tool)
Run PASS: v3.0 -> v2.0 (Tool)
Run PASS: v3.0 -> v1.2 (Tool)
Run ***FAILED***: v3.0 -> fix (Tool)
Run ***FAILED***: v2.2 -> master (Tool)
Run ***FAILED***: v2.2 -> v3.1 (Tool)
Run PASS: v2.2 -> v3.0 (Tool)
Run ***FAILED***: v2.2 -> v2.2 (Tool)
Run PASS: v2.2 -> v2.1 (Tool)
Run PASS: v2.2 -> v2.0 (Tool)
Run PASS: v2.2 -> v1.2 (Tool)
Run ***FAILED***: v2.2 -> fix (Tool)
Run ***FAILED***: v2.1 -> master (Tool)
Run PASS: v2.1 -> v3.1 (Tool)
Run PASS: v2.1 -> v3.0 (Tool)
Run PASS: v2.1 -> v2.2 (Tool)
Run PASS: v2.1 -> v2.1 (Tool)
Run PASS: v2.1 -> v2.0 (Tool)
Run PASS: v2.1 -> v1.2 (Tool)
Run ***FAILED***: v2.1 -> fix (Tool)
Run PASS: v2.0 -> v2.0 (Tool)
Run ***FAILED***: v2.0 -> fix (Tool)
Run PASS: v1.2 -> v1.2 (Tool)
Run PASS: v1.2 -> fix (Tool)
Run ***FAILED***: fix -> master (Tool)
Run PASS: fix -> v3.1 (Tool)
Run PASS: fix -> v3.0 (Tool)
Run PASS: fix -> v2.2 (Tool)
Run PASS: fix -> v2.1 (Tool)
Run PASS: fix -> v2.0 (Tool)
Run PASS: fix -> v1.2 (Tool)
Run PASS: fix -> fix (Tool)
```
It does seem to at least help the clients, solving most of those problems. What I would like to see, however, is someone addressing #1259 - i.e., perform a git-bisect and identify the last known place where we cleanly pass xversion. Let's see what the complete cause of the problem is - it could be that we simply weren't correctly testing before and it never really cleanly passed.

FWIW: I did a line-by-line comparison of master to v3.1 and the only changes I could find in communication paths were the htonl/ntohl ones - which means there is something deeper wrong here.

**Comment by artpol84** [comment]
I suggest going step by step.
This revert in needed no matter what.
The remaining issues are not related to 3.1 and should not delay the release process

**Comment by rhc54** [comment]
And we know that there are no other contributing factors...how? You need to separate your desires to push the release from getting the code base stabilized. We weren't testing much of this before - let's take a little time and establish a true baseline.

**Comment by artpol84** [comment]
To make code stable, please stop pushing commits without any review.
The PR that introduce this issue was merged quickly without any comments requested.
It’s not a single situation. You merge extremely fast when you need. We never merge I reviewed PRs.

**Comment by rhc54** [comment]
Again, the problem here is that our CI tests failed us - an error in the tests caused us to believe that the commits were good. Now that the tests have apparently been fixed (which we need to verify), let's establish a baseline and move forward.

We don't yet know what is causing the full problem, so let's stop worrying about assigning blame and instead focus on identifying causes and fixing things. I have no issue doing that myself, but it will have to fit within my employer's priorities.

**Comment by artpol84** [comment]
This is not blaming. I’m just pointing to a best practices existing in many other projects.
I’m advocating for this for a long time and not being heard. Review is not an optional thing it is **required**.

But in order to do that the code has to be readable. Gigantic commits are not reviewable and not git-bisectable.
In #1259 you suggest to git bisect, but it’ll give much less of a help if we will hit one of those gigantic ones.

CI does not cover all of the cases, so review is a required parallel check. 
I raised the flag back in #1238 but it was already merged in.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f556e17bda0f9c4f2261100cd652e916

**Pull request merged**
