### PR TITLE
client/get: Fix memory race in PMIx_Get

### PR DESCRIPTION
**Pull request by jjhursey**
* Port over the atomics and thread support from `master`
 * Bring over changes from `master` PR #384

### CODE REVIEW

**Comment by rhc54** [comment]
Ugh - you really want to bring that much over? I'll support you if you think it's really necessary. Just a lot of code  for what ultimately is a tiny change, and I can't help but wonder if there might be some smaller (maybe more "hacky") solution for the older release series (e.g., just spin for a little bit?).

**Comment by jjhursey** [comment]
Yeah I'll think about that over the weekend. Maybe we can just grab the atomics portion, and not the threaded portion. In my development build while debugging I just hard coded the PPC instructions, but for portability of pmix in general I'd want to pull over the whole atomics discovery mechanism.

I need to port this back to the `v1.2` series. Actually I also need to port it back to the `v1.1` series. Since `v1.1` is closed I'll just keep that patch internal - but since the two branches are similar the patch will likely look the same.

**Comment by rhc54** [comment]
I have no issue with pulling it into v1.1 if needed - I don't think it's being used outside of you folks, and so I doubt there is an issue. If you need the PPC instructions, then pulling the whole thing over may be the best option. See my comments on #384 - we may have to pull it over just to fix the threading model anyway.

**Comment by jjhursey** [comment]
PR #387 Replaces this PR - streamlining a bit.

**Pull request closed without merging**
