### PR TITLE
v1.1 Fixed faulty compares in PMI/PMI2 tests

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>
(cherry picked from commit 4118eed8a9acaa6948e0069fb65fb411ffa3d94f)

Conflicts:
	test/pmi2_client.c
	test/pmi_client.c

### CODE REVIEW

**Comment by artpol84** [comment]
@karasevb 
```
06:13:26 ++ ls '/var/lib/jenkins/jobs/gh-pmix-pr/workspace/out/out.*'
06:13:26 ls: cannot access /var/lib/jenkins/jobs/gh-pmix-pr/workspace/out/out.*: No such file or directory
06:13:26 + '[' 1 -gt 0 ']'
06:13:26 + echo 'not ok 13 key replacement (./pmix_test -n 5 --test-replace 100:0,1,10,50,99 -o $OUTDIR/out)'
06:13:26 + test_ret=1
06:13:26 + rm '/var/lib/jenkins/jobs/gh-pmix-pr/workspace/out/*'
06:13:26 rm: cannot remove ‘/var/lib/jenkins/jobs/gh-pmix-pr/workspace/out/*’: No such file or directory
```

Please check that we are not running out of space

**Comment by karasevb** [comment]
@artpol84 there is no space issue. This types of test are not supported for PMIx v1.1. I'm going to fix jenkins to exclude those test for v1.1.

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
I appreciate the effort, but we aren't going to fix anything in v1.1 - it is out of maintenance.

**Pull request closed without merging**
