### PR TITLE
Remove unnecessary error log

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/700d17f88bd33535b9f1d8f19efcfe0e

**Comment by rhc54** [comment]
bot:ibm:xver:retest

**Comment by rhc54** [comment]
bot:ibm:xvertool:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9a67c1d184a44ef620452d0e585617c8

**Comment by rhc54** [comment]
@jjhursey We seem to be having IBM CI problems - looks like it may be having network connections again?

**Pull request merged**
