### PR TITLE
Updates for thread safety

### PR DESCRIPTION
**Pull request by rhc54**
@jjhursey Please review

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey Could you please re-review this? I have added all the cherry-picks needed to reach what I believe can be rc2.

**Comment by jjhursey** [comment]
yeah I'll take a look at it today

**Comment by jjhursey** [comment]
@artpol84 I'm not sure about the Jenkins failure. At the bottom of the log there is a message indicating that it's using a deprecated that cannot be found. So it was going to set this to `SUCCESS` but instead set it to failure. That doesn't make sense to me.
```
16:55:07 [Set GitHub commit status (universal)] SUCCESS on repos [GHRepository@8345d11[description=PMIx master repository,homepage=<null>,name=pmix,license=<null>,fork=false,size=5916,milestones={},language=C,commits={},source=<null>,parent=<null>,url=https://api.github.com/repos/pmix/pmix,id=44704948]] (sha:6d56334) with context:gh-pmix-pr
16:55:07 Setting commit status on GitHub for https://github.com/pmix/pmix/commit/6d563342d000a8fcb6200e3b223c29379c75afa6
16:55:07 ERROR: [GitHub Commit Status Setter] - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}, setting build result to FAILURE
16:55:07 
Build step 'Set build status on GitHub commit [deprecated]' changed build result to FAILURE
```

**Comment by jjhursey** [comment]
@rhc54 Any reason why these two commit sets were left out:
 * https://github.com/pmix/pmix/commit/d1a9e5f21273a976c0eea520cd457a468c596cd4
 * https://github.com/pmix/pmix/commit/d99e1b49eef109f16b4c6bea15b961065e9a6a90

Otherwise I think you got them all.

**Comment by artpol84** [comment]
```
16:55:07 ERROR: [GitHub Commit Status Setter] - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}, setting build result to FAILURE
```
Seems like a Github-side issue. I will run this with our guys internally.

Technically all tests have OK status, so I think we can consider it as successful check.

**Comment by rhc54** [comment]
I honestly don't know how I missed those two - thanks!

**Pull request merged**
