### PR TITLE
Modification of connect/disconnect APIs

### PR DESCRIPTION
**Pull request by rhc54**
Refs https://github.com/pmix/RFCs/pull/3

### CODE REVIEW

**Comment by artpol84** [comment]
bot:retest

**Comment by rhc54** [comment]
This has died - no point in pursuing it

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/96854982f63abe2c7ae2e9b461801864

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b30d8a527379874ac3a01f60896487ab

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bdb7771148979fbd0e7ee1c63c443fc0

**Comment by jjhursey** [comment]
@rhc Did you reopen this PR, or did GH automatically do it for you?

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/5b2983cf84904df552d200d7d0d34635

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/89cab5cb611ab795520de551959f9c0a

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7cd3357d7ea9ba62e5a263d19e056ded

**Comment by rhc54** [comment]
@jjhursey Yes, I intentionally re-opened it per my email to the devel list. I have now updated the code to sync with PMIx master

**Comment by rhc54** [comment]
odd - the failing tests run correctly on my machine. let's try it again

bot:mellanox:retest

**Pull request merged**
