### PR TITLE
Addressed the dstore compatibility between v2.1 and v.2.0

### LINKED ISSUE #498: dstore compatibility between v2.1 and v2.0
I've done a little light testing of v2.1 vs v2.0 dstore, and the two appear to be incompatible. If I set PMIX_DEBUG=20 and PMIX_MCA_gds_base_verbose=20 in the environment, and then run a v2.1 server with a v2.0 client, I get the following:
```
$ ./simptest -e /home/common/pmix/v2.0/test/simple/simpclient
Testing version 2.1.0
[rhc001:56080] mca: base: component_find: searching (null) for gds components
[rhc001:56080] mca: base: find_dyn_components: checking (null) for gds components
[rhc001:56080] pmix:mca: base: components_register: registering framework gds components
[rhc001:56080] pmix:mca: base: components_register: found loaded component ds12
[rhc001:56080] pmix:mca: base: components_register: component ds12 has no register or open function
[rhc001:56080] pmix:mca: base: components_register: found loaded component hash
[rhc001:56080] pmix:mca: base: components_register: component hash has no register or open function
[rhc001:56080] mca: base: components_open: opening gds components
[rhc001:56080] mca: base: components_open: found loaded component ds12
[rhc001:56080] mca: base: components_open: component ds12 open function successful
[rhc001:56080] mca: base: components_open: found loaded component hash
[rhc001:56080] mca: base: components_open: component hash open function successful
[rhc001:56080] mca:gds:select: checking available component ds12
[rhc001:56080] mca:gds:select: Querying component [ds12]
[rhc001:56080] pmix:gds:dstore init
[rhc001:56080] mca:gds:select: checking available component hash
[rhc001:56080] mca:gds:select: Querying component [hash]
[rhc001:56080] gds: hash init
[rhc001:56080] Final gds priorities
[rhc001:56080] 	gds: ds12 Priority: 20
[rhc001:56080] 	gds: hash Priority: 10
[rhc001:56080] pnet: opa init
[rhc001:56080] pmix:server init called
[rhc001:56080] pmix_register_event_hdlr shifting to progress thread
[rhc001:56080] pmix: register event_hdlr with 1 infos
[rhc001:56080] pmix: _add_hdlr
[rhc001:56080] SERVER: ERRHANDLER REGISTRATION CALLBACK CALLED WITH STATUS 0, ref=0
[rhc001:56080] pmix_register_event_hdlr shifting to progress thread
[rhc001:56080] pmix: register event_hdlr with 1 infos
[rhc001:56080] pmix: _add_hdlr
[rhc001:56080] pmix:server _register_nspace foobar
[rhc001:56080] gds: dstore add nspace
[rhc001:56080] gds_dstore.c:856:_esh_session_init _lockfile_name: /tmp/pmix_dstor_56080/dstore_sm.lock
[rhc001:56080] gds_dstore.c:1014:_create_new_segment: segment type 0, nspace foobar, id 0
[rhc001:56080] [pmix-server:56080] gds:hash:cache_job_info for nspace foobar
[rhc001:56080] HASH:STORE rank -2 key pmix.univ.size
[rhc001:56080] HASH:STORE rank -2 key pmix.spawned
[rhc001:56080] HASH:STORE rank -2 key pmix.local.size
[rhc001:56080] HASH:STORE rank -2 key pmix.lpeers
[rhc001:56080] pmix:extract:nodes: checking list: rhc[3:1]
[rhc001:56080] regex:extract:nodes: parsing range rhc 1 (null)
[rhc001:56080] regex:parse:ranges: parse range 1 (2)
[rhc001:56080] [pmix-server:56080] gds:hash:store_map
[rhc001:56080] HASH:FETCH rank -2 key rhc001
[rhc001:56080] HASH:FETCH data for key rhc001 not found
[rhc001:56080] HASH:STORE rank -2 key rhc001
[rhc001:56080] HASH:STORE rank 0 key pmix.hname
[rhc001:56080] HASH:STORE rank -2 key pmix.nlist
[rhc001:56080] HASH:STORE rank -2 key pmix.job.size
[rhc001:56080] HASH:STORE rank -2 key pmix.usock.disable
[rhc001:56080] pmix:server setup_fork for nspace foobar rank 0
[rhc001:56080] gds: dstore setup fork
[rhc001:56080] pmix:server register client foobar:0
[rhc001:56080] pmix:server _register_client for nspace foobar rank 0
[rhc001:56097] posting notification recv on tag 0
[rhc001:56097] pnet: opa init
[rhc001:56097] pmix: init called
[rhc001:56097] dstore/pmix_esh.c:893:_esh_init
[rhc001:56097] dstore/pmix_esh.c:801:_esh_session_init _lockfile_name: /tmp/pmix_dstor_56080/dstore_sm.lock
[rhc001:56097] dstore/pmix_esh.c:1697:_attach_new_segment: segment type 0, nspace foobar, id 0
[rhc001:56097] ptl_base_connect: attempting to connect to server
[rhc001:56097] usock_peer_try_connect: attempting to connect to server on socket 7
[rhc001:56097] send blocking of 53 bytes to socket 7
[rhc001:56097] blocking send complete to socket 7
[rhc001:56097] waiting for blocking recv of 4 bytes
[rhc001:56080] psec: native validate_cred ?
[rhc001:56080] psec: native credential 1000:1000 valid
[rhc001:56080] credential validated
[rhc001:56097] blocking receive complete from remote
[rhc001:56097] waiting for blocking recv of 4 bytes
[rhc001:56097] blocking receive complete from remote
[rhc001:56097] sock_peer_try_connect: Connection across to server succeeded
[rhc001:56097] pmix_bfrop_pack_int16 * 1
[rhc001:56097] pmix_bfrop_pack_int32 * 1
[rhc001:56097] pmix_bfrop_pack_buffer( 0x1019e10, 0x7ffce14f18bc, 1, 14 )
[rhc001:56097] pmix_bfrop_pack_int16 * 1
[rhc001:56097] pmix_bfrop_pack_int32 * 1
[rhc001:56097] foobar:0 ptl:base:recv:handler called with peer pmix-server:56080
[rhc001:56097] ptl:base:recv:handler allocate new recv msg
[rhc001:56097] ptl:base:recv:handler read hdr on socket 7
[rhc001:56097] posting recv on tag 101
[rhc001:56097] QUEIENG MSG TO SERVER OF SIZE 12
[rhc001:56097] foobar:0 ptl:base:send_handler SENDING TO PEER pmix-server:56080 tag 101 with NON-NULL msg
[rhc001:56097] ptl:base:send_handler SENDING MSG
[rhc001:56097] ptl:base:send_handler MSG SENT
[rhc001:56080] SWITCHYARD for foobar:0:10
[rhc001:56080] recvd pmix cmd 0 from foobar:0
[rhc001:56080] [pmix-server:56080] gds:hash:register_job_info for peer [foobar:0]
[rhc001:56080] [pmix-server:56080] gds:hash:register_info
[rhc001:56080] pmix:gds:hash packing job info pmix.univ.size
[rhc001:56080] pmix:gds:hash packing job info pmix.spawned
[rhc001:56080] pmix:gds:hash packing job info pmix.local.size
[rhc001:56080] pmix:gds:hash packing job info pmix.lpeers
[rhc001:56080] pmix:gds:hash packing job info pmix.nmap
[rhc001:56080] pmix:extract:nodes: checking list: rhc[3:1]
[rhc001:56080] regex:extract:nodes: parsing range rhc 1 (null)
[rhc001:56080] regex:parse:ranges: parse range 1 (2)
[rhc001:56080] pmix:gds:hash packing job info pmix.pmap
[rhc001:56080] pmix:gds:hash packing job info pmix.job.size
[rhc001:56097] foobar:0 ptl:base:recv:handler called with peer pmix-server:56080
[rhc001:56097] ptl:base:recv:handler read hdr on socket 7
[rhc001:56097] RECVD MSG FOR TAG 101 SIZE 315
[rhc001:56097] ptl:base:recv:handler allocate data region of size 315
[rhc001:56097] foobar:0 RECVD COMPLETE MESSAGE FROM SERVER OF 315 BYTES FOR TAG 101 ON PEER SOCKET 7
[rhc001:56097] [base/ptl_base_sendrecv.c:495] post msg
[rhc001:56097] foobar:0 message received 315 bytes for tag 101 on socket 7
[rhc001:56097] checking msg on tag 101 for tag 101
[rhc001:56097] foobar:0 EXECUTE CALLBACK for tag 101
[rhc001:56097] pmix_bfrop_unpack_int16 * 1
[rhc001:56097] pmix_bfrop_unpack_int32 * 1
[rhc001:56097] pmix_bfrop_unpack: found 1 values for 1 provided storage
[rhc001:56097] pmix_bfrop_unpack_buffer( 0x7f21c6d3bcf0, 0x7f21c6d3bba8, 1, 3 )
[rhc001:56097] pmix_bfrop_unpack_int16 * 1
[rhc001:56097] pmix_bfrop_unpack_int32 * 1
[rhc001:56097] pmix_bfrop_unpack_byte * 7
[rhc001:56097] foobar:0 CALLBACK COMPLETE
[rhc001:56097] pmix: get_nb value for proc foobar:4294967294 key pmix.dbg.init
[rhc001:56097] pmix: getnbfn value for proc foobar:-2 key pmix.dbg.init
[rhc001:56097] HASH:FETCH rank -2 key pmix.dbg.init
[rhc001:56097] HASH:FETCH proc data for rank -2 not found
[rhc001:56097] dstore/pmix_esh.c:1198:_esh_fetch: for foobar:4294967294 look for key pmix.dbg.init
[rhc001:56097] dstore/pmix_esh.c:1880:_update_initial_segment_info
[rhc001:56097] dstore/pmix_esh.c:1904:_get_ns_info_from_initial_segment
[rhc001:56097] dstore/pmix_esh.c:1254:_esh_fetch:  no data for ns foobar is found in the shared memory.
[rhc001:56097] pmix:client get completed -17
[rhc001:56097] client: notifying server foobar:0 of status PMIX MODEL DECLARED
[rhc001:56097] foobar:0 invoke_local_event_hdlr for status PMIX MODEL DECLARED
[rhc001:56097] pmix_client_notify_event source = foobar:0 event_status =-147, rc=0
[rhc001:56097] Client ns foobar rank 0: Running
[rhc001:56097] pmix: get_nb value for proc foobar:4294967294 key pmix.job.size
[rhc001:56097] pmix: getnbfn value for proc foobar:-2 key pmix.job.size
[rhc001:56097] HASH:FETCH rank -2 key pmix.job.size
[rhc001:56097] HASH:FETCH proc data for rank -2 not found
[rhc001:56097] dstore/pmix_esh.c:1198:_esh_fetch: for foobar:4294967294 look for key pmix.job.size
[rhc001:56097] dstore/pmix_esh.c:1880:_update_initial_segment_info
[rhc001:56097] dstore/pmix_esh.c:1904:_get_ns_info_from_initial_segment
[rhc001:56097] dstore/pmix_esh.c:1254:_esh_fetch:  no data for ns foobar is found in the shared memory.
[rhc001:56097] pmix:client get completed -17
[rhc001:56097] Client ns foobar rank 0: PMIx_Get failed: PROC-ENTRY-NOT-FOUND
[rhc001:56080] pmix_server: notify client of event PMIX MODEL DECLARED
[rhc001:56080] pmix_server_notify_event status =-147, source = pmix-server:56080, ninfo =3
[rhc001:56080] pmix_server_notify_event source = pmix-server:56080 event_status = -147, rc= 0
[rhc001:56080] pmix_server: _notify_client_event notifying clients of event PMIX MODEL DECLARED range UNKNOWN type NONDEFAULT
[rhc001:56080] pmix-server:56080 invoke_local_event_hdlr for status PMIX MODEL DECLARED
[rhc001:56080] [event/pmix_event_notification.c:765] INVOKING EVHDLR SIMPTEST-MODEL
SIMPTEST: Model event handler called with status -147(PMIX MODEL DECLARED)
	pmix.pgm.model:	PMIX
	pmix.mdl.name:	test
	pmix.evname:	SIMPTEST-MODEL
[rhc001:56080] pmix_deregister_event_hdlr shifting to progress thread
[rhc001:56080] pmix:server finalize called
[rhc001:56080] pnet: opa finalize
[rhc001:56080] gds_dstore.c:2113:dstore_finalize
[rhc001:56080] sys call unlink(2) fail
[rhc001:56080] gds: hash finalize
[rhc001:56080] mca: base: close: component ds12 closed
[rhc001:56080] mca: base: close: unloading component ds12
[rhc001:56080] mca: base: close: component hash closed
[rhc001:56080] mca: base: close: unloading component hash
[rhc001:56080] pmix:server finalize complete
Test finished OK!
```

Note that the PMIx_Get failed in dstore as it believes it has no data for the given nspace. I see that the request for job-level info was received by the server, but it looks like it used the hash component to send the data back to the client instead of moving it into a shmem segment, as the client expected. Could be just something wrong in selecting the correct gds component for the peer? I'll look a little more into that possibility, but wanted to track this problem.

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>

Closes #498 

PR is in progress. Don't merge. 

There are results of testing for v2.1 server with v2.0 clients:
```
/pmix/v2.1/test $ ./check.sh
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:3]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[d | 0:]" --noise [0:0,1] -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --job-fence -c -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --job-fence -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-publish -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-spawn -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-connect -e /home/user/pmix/v2.0/test/.libs/pmix_client
FAIL ./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 5 --test-replace 100:0,1,10,50,99 -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 5 --test-internal 10 -e /home/user/pmix/v2.0/test/.libs/pmix_client
```

### CODE REVIEW

**Comment by rhc54** [comment]
I confess I'm still scratching my head over the pack/unpack operations in dstore. I can see that you might need something for backward compatibility, but why isn't there a new component then that avoids all that overhead going into the future?

I'd need to look a little closer at the proposed changes - I'm a little concerned about re-assigning the client server's compat pointers in mid operation as they get used elsewhere.

**Comment by rhc54** [comment]
@karasevb If you are holding back from committing due to the resolve peers test, the issue is likely to be that we no longer break down the node/proc map and store the individual data. So in PMIx v2.1, the resolve_peers API calls retrieve the maps and parse them to get the answer, whereas in earlier versions we parsed the maps and stored every proc's node information separately - and thus resolve_peers just did a "get" to retrieve it.

What you'll have to do is break the data down for clients that are v2.0 and earlier. I provide macros for determining the version of a client - see PMIX_PROC_IS_V1 and friends in src/mca/ptl/ptl_types.h

**Comment by karasevb** [comment]
@rhc54 I have solved the resolving peers issue, and I'm working on new dstor component. I will add the uses `PMIX_PROC_IS_V1` as you advised for faster closing this PR. This will done today in my timezone.
And the new dstor component will provided in another PR.

**Comment by karasevb** [comment]
All backward compatibility checks are passed:
```
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:3]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[d | 0:]" --noise [0:0,1] -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --job-fence -c -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --job-fence -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-publish -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-spawn -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 2 --test-connect -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 5 --test-replace 100:0,1,10,50,99 -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 5 --test-internal 10 -e /home/user/pmix/v2.0/test/.libs/pmix_client
```

**Comment by karasevb** [comment]
PR is ready to merge.

**Comment by rhc54** [comment]
Thanks!

**Comment by rhc54** [comment]
Thank you! Will merge tonight

**Pull request merged**
