### PR TITLE
v3.x/Flexible integer packing with psquash framework in bfrops 

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1152 
Includes fixes #1171 

Depends on #1173, #1175

### CODE REVIEW

**Comment by jjhursey** [comment]
Ref issue #1169

**Comment by jjhursey** [comment]
From this week's teleconf:
 * Cross version test script enhancement request (separate from this PR)
   - https://github.com/pmix/pmix-tests/issues/4
 * Creating a `bfrops/v32` component seems like the correct path
 * During the client/server handshake we need to make sure both sides are using the same `psquash` component since the normal traffic between the client and server packs/unpacks data so both sides need to be using the same `bfrops` and `psquash` components.
   - Consider the scenario where the client is using (bfrops/v32 + psquash/flex128) and the server is using (bfrops/v32 + psquash/native). Now the encoding mismatch will cause a conflict.
   - The suggestion was that if the server picks the `bfrops/v32` component then the client is forced to use the matching `psquash` component (probably `flex128`). This is a short term solution.
      - The user can always fall back to `bfops/v31` if they hit any issues with the `psquash/flex128` component (or framework).
   - Longer term we need the `psquash` framework to be multi-select and allow the handshake to pick the most compatible version.
      - I created https://github.com/pmix/pmix/issues/1184 to track that enhancement request.

**Comment by artpol84** [comment]
@karasevb lets discuss this

**Comment by jjhursey** [comment]
Any progress on this discussion?

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b8acfba24f374a0f4dd0531a418de00b

**Comment by rhc54** [comment]
@karasevb @artpol84 Please retarget v3.2 branch

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/9ff00f280f7ed12b1477ad57d221c3b6

**Comment by karasevb** [comment]
Closed by #1423

**Pull request closed without merging**
