### PR TITLE
memory usage probe tool for mpi process/daemon

### PR DESCRIPTION
**Pull request by dong0321**
Memory usage information comes from  /proc/pid/smaps, /proc/pid/maps and /proc/pid/status.

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by artpol84** [comment]
@dong0321 I think this tool is not related with pmix_perf.
I think it is better to keep them in different directories.
Can you move your files to a dir and once this PR is merged I'll push pmix_perf files in pmix_perf dir

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
check if jenkins changes breaking current pmix test suite

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
Please reopen if you want this included at some future date

**Pull request closed without merging**
