### PR TITLE
Travis CI Script

### PR DESCRIPTION
**Pull request by ax3l**
Draft for adding travis-ci for memory checks: #1025 https://github.com/open-mpi/ompi/issues/6242

## Open Questions

- [x] are there automated unit tests? `make check` or `cd test && make all`? They seem to need an installed `help-pmix-runtime.txt` but can one test those without the need to install to a system path first (aka: avoid `sudo`)?

## To Do

- [x] add badge
- [x] add libevent
- [ ] general flags: `-Werror -Wall -Wextra` and maybe `-pedantic -Wshadow`
- [ ] add `-fsanitize=address` for tests in an entry

### CODE REVIEW

**Comment by ax3l** [comment]
@rhc54 can you recommend any executables/tests that I can use to check for memleaks?

**Comment by rhc54** [comment]
@ggouaillardet Can you please take a look?

**Comment by artpol84** [comment]
Hello,
We are using unit tests located in tests directory.
Our Jenkins scripts can be used as the reference.

**Comment by ax3l** [comment]
Hi @artpol84,

is there a common target to run all unit tests? Somehow it does not look self-explanatory to me. Where are the jenkins scripts located?

**Comment by artpol84** [comment]
This is the script we are using.
https://github.com/mellanox-hpc/jenkins_scripts/tree/master/jenkins/pmix
I don’t think we have Make target for it, but we can create it if needed.

**Comment by ax3l** [comment]
@artpol84 thank you. yes, can you please add a simple `make check` or `make test` target for it? That would be great, also for local tests! :)

**Comment by artpol84** [comment]
@karasevb, please add to your TODO list

**Comment by ax3l** [comment]
Just out of curiosity, did you find time to add the `test` targets?

**Comment by artpol84** [comment]
Not yet unfortunately. @karasevb is occupied with more urgent thing.

**Comment by ax3l** [comment]
Ok, no problem. Just ping we when it's ready :)

**Comment by rhc54** [comment]
@ax3l Sorry for the delay - I have added "make check" support in the "tests" subdirectory with PR #1197 

HTH

**Comment by ax3l** [comment]
@rhc54 can you activate Travis-CI.org for this repo under https://travis-ci.org/account/repositories ?

**Comment by rhc54** [comment]
I _think_ I did it - let me know

**Comment by rhc54** [comment]
fwiw: i was able to manually trigger a Travis test on master, which failed of course as the travis.yml file isn't in it yet

**Comment by rhc54** [comment]
@ax3l Do you want me to commit this script so we can see what Travis does with it?

**Comment by ax3l** [comment]
We can try it here so far: https://travis-ci.org/ax3l/pmix
Seams there is one test failing or at least some return code is non-zero. Does the output therein make sense to you?

**Comment by rhc54** [comment]
Yes, that is the correct output. I'm not sure why, but I saw 1-2 tests failing for some reason. One failed every time, but the other looked like a race condition as it only failed occasionally. Our CI supposedly is also running those tests and yet passes, so I don't know if the tests are supposed to fail (which my script doesn't recognize yet), or if the CI isn't running those tests (and so we don't realize we have a problem), or...? We are going to discuss it on today's devel call.

For now, though, I'd say your yml looks good!

**Comment by rhc54** [comment]
@ax3l We good to go? I'm not worried about the test failing at the moment as we'll get that fixed.

**Comment by jjhursey** [comment]
Per teleconf:
 * @artpol84 is [this version](https://github.com/pmix/pmix/blob/master/contrib/pmix_jenkins.sh) of the jenkins script up to date with what Mellanox is running?
 * There were two tests failing in `make check` that the Jenkins script was not flagging in CI. Someone should take a look. Can Mellanox confirm their CI setup and make sure this isn't silently slipping through? Thanks!

**Comment by rhc54** [comment]
I have reviewed the output from a Mellanox Jenkins run and corrected the list of tests - there were indeed differences. The test script now passes. The remaining issue I'm working on is resolving the shared library problem - the tests require linking against the PMIx plugins (which are shared libraries), and so those libraries must be "found" when the tests execute.

For now, if you configure with ```--disable-dlopen``` everything will work fine. I have a PR (#1202) to link everything up correctly, but ```make tarball``` is having issues with it that still need to be worked out. Hope to have that resolved soon. Meantime, it works fine for simply building and running ```make check```, so I am going to leave ```make tarball``` hardcoded to disable dlopen and bring the rest of the changes into the repo after a little more testing (hopefully tomorrow).

**Comment by ax3l** [comment]
@rhc54 thank you for the updates, the script is passing now.
Somehow it looks like only one test is run, is that correct?

**Comment by rhc54** [comment]
No, there are actually closer to 10 tests being run by the test script. However, since it is a script running it, `make check` only sees it as a single reporting executable. I'll follow up by having the script only run one executable and then have `make check` invoke it multiple times so they report separately.

**Comment by rhc54** [comment]
@ax3l I have updated the tests so that they report independently - there are 16 of them. I note that a couple of your check boxes were still open. Please feel free to re-open this or create a new PR to complete what you wanted to do.

**Pull request merged**
