### PR TITLE
Fix/v3.0/cli connect v2

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
I will ask @karasevb to run xversion manually to confirm that this is working fine

**Comment by artpol84** [comment]
@rhc54 @ax3l Do we have travis for this branch?

**Comment by ax3l** [comment]
@artpol84 you just need to merge the `.travis.yaml` from `master` for it :)

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0ed260725a2b6d00f8e3d2d6e346ec92

**Pull request merged**
