### PR TITLE
v3.x/bfrops: redefinition regtypes for internal usage

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1144.
Includes fixes: #1170, #1161, #1155

### CODE REVIEW

**Comment by jjhursey** [comment]
Ref issue #1169

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/563d5d1a115f293f7882bf6e6b5315e9

**Comment by rhc54** [comment]
@karasevb @artpol84 Please retarget v3.2 branch

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/30c228d3ec206bd9e94598dce577efbe

**Comment by karasevb** [comment]
Replaced by #1402

**Pull request closed without merging**
