### PR TITLE
Multiserver test check

### PR DESCRIPTION
**Pull request by karasevb**
This PR cannot be merged, it reverts the repo state until PR 897 only for testing goals. 
The goal is to test the new multi-server test mode with PR #897, to make sure #952 is able to catch modex bugs like described here #902

### CODE REVIEW

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by karasevb** [comment]
Will reopen

**Comment by karasevb** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
@karasevb, perfect!!

@jjhursey, @rhc54, FYI.

**Comment by jjhursey** [comment]
@karasevb Just to confirm my understanding of this investigation PR.
PR #897 had a data corruption bug in it that was fixed in PR #902. In this PR you verified that CI will now correctly catch the error if it happens again.
Thanks!

**Comment by karasevb** [comment]
@jjhursey yes, that is right

**Pull request closed without merging**
