### PR TITLE
v3.x/modex: reduce modex size by replacing key names with indexes 

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #1149 
Includes fixes: #1168 

Depends on #1174.

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54 @jjhursey are we good to go?

**Comment by rhc54** [comment]
Still waiting on release of v3.1.3 - holding for completion and backport of #1193

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/083a621db58efafca0f9d5ed1a3ac4d6

**Comment by rhc54** [comment]
@karasevb @artpol84 Please retarget v3.2 branch

**Comment by karasevb** [comment]
Closed by #1421

**Pull request closed without merging**
