### PR TITLE
Implement pnet/test sched support

### PR DESCRIPTION
**Pull request by rhc54**
Provide a simple test component for the scheduler interfaces
along with a simpsched test that exercises them.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/957f73b28525efb8e295979b71c6fa90

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c0b95dd44e368204bee5c670fc70e855

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fe8b96863feb22c04a0c1b90fcfe10c7

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a1208168d206fdcd737c782a432bf93c

**Comment by rhc54** [comment]
@jjhursey I gather something changed in the CI as we are now seeing separate client and tool xversion reports - yes? I cannot replicate the client xversion failures, so I suspect something in the revision isn't quite correct. Best I can tell when running by hand, this PR passes all client xversion tests.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/830f77bf86574ce3806b33985e59e042

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0d4f962763f3ae92683fbcccb5cd1e60

**Pull request merged**
