### PR TITLE
bfrops: redefinition regtypes for internal usage

### LINKED ISSUE #1099: Generalize `bfrops` components
According to Issue #681, I'm working on the implementation of new flexible packing with a new component `bfrops`.
My question is to avoid duplication of code and simplify future bfrops multi-component support.

**Details:**
I forked bfrops v3 to v4 and modified it for use new flexible packing by changing pack/unpack registration functions. We want to use new pack/unpack functions for all integer types. For integer-based PMIx types (like `PMIX_INT16`, `PMIX_INT32`, `PMIX_SIZE` etc) is not a problem to replace registration functions to new:
```C
    PMIX_REGISTER_TYPE("PMIX_SIZE", PMIX_SIZE,
                       pmix4_bfrops_base_pack_int_flex, <- replaced
                       pmix4_bfrops_base_unpack_int_flex, <-replaced
                       ...
                       &mca_bfrops_v4_component.types);
```
The complex PMIx types, such as `PMIX_DATA_ARRAY`, `PMIX_KVAL`, etc., directly call into its implementation a simple-integer packing functions. 
Let's consider a packing for `PMIX_DATA_ARRAY`:
```C
    PMIX_REGISTER_TYPE("PMIX_DATA_ARRAY", PMIX_DATA_ARRAY,
                       pmix_bfrops_base_pack_darray,
                       pmix_bfrops_base_unpack_darray,
                       ...
```
The function `pmix_bfrops_base_pack_darray` uses `pmix_bfrops_base_pack_int64` direclty:
https://github.com/pmix/pmix/blob/0f7075f7d204b3cf46ef2aa43120632696cd858a/src/mca/bfrops/base/bfrop_base_pack.c#L883

**The issue is in following:** to implement the new bfrops component, that has foreign simple-packing integer methods it requires a full duplicate of implementation of complex-packing PMIx types. For example: for `pmix_bfrops_base_pack_darray` will require to call new `pmix_bfrops_base_pack_int64`, that require a duplicate of `pmix_bfrops_base_pack_darray` with new int64 packing. 

The multiple duplications is not a right way. So I would like to propose another way, that requires to modify a prototype of pack/unpack methods by adding `pmix_pointer_array_t *regtypes` to each one.
Example of `pmix_bfrops_base_pack_darray` modification:
```patch
 pmix_status_t pmix_bfrops_base_pack_darray(pmix_buffer_t *buffer, const void *src,
-                                           int32_t num_vals, pmix_data_type_t type)
+                                           int32_t num_vals, pmix_data_type_t type,
+                                           pmix_pointer_array_t *regtypes)
 {
     pmix_data_array_t *p = (pmix_data_array_t*)src;
     pmix_status_t ret;
     int32_t i;
+    pmix_bfrop_type_info_t *info;
 
     for (i=0; i < num_vals; i++) {
+        /* Lookup the pack function for this type and call it */
+        if (NULL == (info = (pmix_bfrop_type_info_t*)pmix_pointer_array_get_item(regtypes, type))) {
+            PMIX_ERROR_LOG(PMIX_ERR_UNKNOWN_DATA_TYPE);
+            return PMIX_ERR_UNKNOWN_DATA_TYPE;
+        }
         /* pack the actual type in the array */
         if (PMIX_SUCCESS != (ret = pmix_bfrop_store_data_type(buffer, p[i].type))) {
             return ret;
@@ -805,190 +812,10 @@ pmix_status_t pmix_bfrops_base_pack_darray(pmix_buffer_t *buffer, const void *sr
             /* nothing left to do */
             continue;
         }
-        /* pack the actual elements - have to do this the hard way */
-        switch(p[i].type) {
-            case PMIX_UNDEF:
-                break;
-            case PMIX_BOOL:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_bool(buffer, p[i].array, p[i].size, PMIX_BOOL))) {
-                    return ret;
-                }
-                break;
-            case PMIX_BYTE:
-            case PMIX_STRING:
-            case PMIX_STRING:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_string(buffer, p[i].array, p[i].size, PMIX_STRING))) {
-                    return ret;
-                }
-                break;
-            case PMIX_SIZE:
-            case PMIX_PID:
-            case PMIX_INT:
...
-            case PMIX_ENVAR:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_envar(buffer, p[i].array, p[i].size, PMIX_ENVAR))) {
-                    return ret;
-                }
-                break;
-
-            default:
-                pmix_output(0, "PACK-PMIX-VALUE[%s:%d]: UNSUPPORTED TYPE %d",
-                            __FILE__, __LINE__, (int)p[i].type);
-            return PMIX_ERROR;
+        ret = info->odti_pack_fn(buffer, p[i].array, p[i].size, p[i].type);
+        if (PMIX_SUCCESS != ret) {
+            PMIX_ERROR_LOG(ret);
+            return ret;
         }
     }
     return PMIX_SUCCESS;

```
` *regtypes` must be passed from the upper abstract level of pack/unpack functions, also should be updated pack/unpack methods for all existed bfrops. 

This way allows keeping a common `pmix_bfrops_base_pack_darray` in base-code, and `odti_pack_fn` will call a specific registered packing method, that can be different between the version of bfrops. This allows reducing of code duplication, and simplify the support. The likewise modification is required other comlex-packing types.

### PR DESCRIPTION
**Pull request by karasevb**
According to https://github.com/pmix/pmix/pull/1130#issuecomment-471073856, this PR re-opens #1126 (Used new PR since the original cannot be reopened).

Closes #1099

### CODE REVIEW

**Comment by karasevb** [comment]
Waiting for MTT results.

**Comment by karasevb** [comment]
MTTs are passed. PR is ready to go.

**Comment by rhc54** [comment]
Could we please run the cross-version test against this branch? Just to verify that it didn't break anything.

**Comment by karasevb** [comment]
The cross-version test is passed exapt that:
```
Run FAIL: v3.1 -> master
Run FAIL: v3.0 -> master
```
Details:
```bash
$ ./simptest -e /labhome/user/pmix_compat/pmix-tests/crossversion/pmix-master/test/simple/simpclient
Testing version 3.1.3a1
[node-019:15107] SERVER: ERRHANDLER REGISTRATION CALLBACK CALLED WITH STATUS 0, ref=0
Collecting inventory
[node-019:15107] INVENTORY RECEIVED
[node-019:15107] INVENTORY READY FOR DELIVERY
Inventory collected: 0
[node-019:15107] PMIX ERROR: UNREACHABLE in file ptl_tcp_component.c at line 1685
[node-019:15110] Client ns foobar rank 0: PMIx_Init failed: UNREACHABLE
Child 0 [15110] exited with status 231 - test FAILED
SIMPTEST: Model event handler called with status -147(PMIX MODEL DECLARED)
        pmix.pgm.model: PMIX
        pmix.mdl.name:  test
        pmix.evname:    SIMPTEST-MODEL
TEST FAILED WITH ERROR 231
```

These failures are not related to this PR, and are reproduced with the master.

**Comment by rhc54** [comment]
Okay we better fix that first so we can ensure this PR doesn’t break it

**Comment by artpol84** [comment]
By its nature this PR is not expected to break backwards compatibility.

@karasevb demonstrated that it doesn't make things worse.
I don't see why should we wait. You already pushed a PR infront of this one causing additional work. We have limited cycles and this wasn't the way I'd like to spend them.

**Comment by rhc54** [comment]
@karasevb I'd prefer to resolve the cross-version issue before committing if we can. Reason I'm so cautious is that I had written a fairly similar PR at one point - it might even have been committed (I honestly don't recall). However, it hit problems and I had to abandon it.

Unfortunately, it has been long enough that I honestly cannot recall the nature of the issue. It's entirely possible it has subsequently been resolved, or that some combination of changes avoids the old issue. I can't remember the state of the bfrops framework when I did that work.

What I'd like to do is have @jjhursey or I update the xversion.py script in pmix-tests so it can checkout and test a PR against master plus all relevant release branches. I am on travel thru Wed and likely won't have time to do this prior to my return, so unless Josh can do it sooner it will be end of the week.

It should be a relatively simple change to the script. If it turns out to be something that would take longer than the end of this week to complete, then we will commit this PR and deal with the cross-version issue afterwards.

Sound okay?

**Comment by karasevb** [comment]
As git bisect showed, the issue of cross-version was started with commit 067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93:
```
$ git bisect bad
067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93 is the first bad commit
commit 067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93
Author: Ralph Castain <rhc@pmix.org>
Date:   Wed Feb 13 20:19:16 2019 -0800

    Simulate assigning network coordinates for OPA

    Remove typo reference to OPAL

    Add bfrops support for new PMIX_COORD datatype
    Properly handle the PMIX_COORD data type
    Must allocate a memory location before copy

    Signed-off-by: Ralph Castain <rhc@pmix.org>

:040000 040000 5cf39ee087ea8dea009b78711c5901cef9ee0292 b78eaaf3e468f9e189b3bb26fe19b8600062c698 M      include
:040000 040000 c039b935d9a19cc8755edd1b6be5e6b573831bb4 484e6742e1039764ec49ca5bb9666bfd91fda3c4 M      src
```
@rhc54 we would like to merge this not independently of the cross-version issue, since it is definitely not related to that PR.

<details>
 <summary>git bisect log</summary>

```
$ git bisect log
git bisect start
# bad: [650a58b7b70c94241da93eb2f9b6d0b48a75ce84] Merge pull request #1145 from rhc54/topic/py
git bisect bad 650a58b7b70c94241da93eb2f9b6d0b48a75ce84
# good: [c3a9e5c4d4f5581e241981070ea5876be21a9b77] test: multiserver fixes
git bisect good c3a9e5c4d4f5581e241981070ea5876be21a9b77
# bad: [13baa77fe2ac3a1cd70f05729875a4a6e1e85de4] Merge pull request #1129 from rhc54/topic/libev
git bisect bad 13baa77fe2ac3a1cd70f05729875a4a6e1e85de4
# bad: [6278d896a30a4aab4cded1a50793c5f43bf76e2f] Merge pull request #1118 from rhc54/topic/coord
git bisect bad 6278d896a30a4aab4cded1a50793c5f43bf76e2f
# good: [ccb76fd4a5745ee8591ff9655a54c2ca9adcdbba] configury: automatically generate PMIX_NUMERIC_VERSION
git bisect good ccb76fd4a5745ee8591ff9655a54c2ca9adcdbba
# good: [81286fcb1ee50d8cabd5f6fa700436e339ef04e1] Remove the "restrict" keyword to avoid requiring C99 for apps
git bisect good 81286fcb1ee50d8cabd5f6fa700436e339ef04e1
# good: [a9429027c3e96e1533912f768b6068907690e304] Use "restrict", but protect it
git bisect good a9429027c3e96e1533912f768b6068907690e304
# bad: [067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93] Simulate assigning network coordinates for OPA
git bisect bad 067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93
# first bad commit: [067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93] Simulate assigning network coordinates for OPA
```
</details>

**Comment by karasevb** [comment]
@ggouaillardet thanks for the advice, but there are many dependent changes to revert.

I suspect that problem is in the following: master-client uses bfrops v4 (that assigns on line 161) while 3.x-server uses bfrops v3:
https://github.com/pmix/pmix/blob/067086e1597ed8a9ad6608f1b4cf5aeb52ae2e93/src/mca/ptl/tcp/ptl_tcp.c#L154-L162

Simple patch avoids issues with cross-test:
<details><summary>patch</summary>

```patch
diff --git a/src/mca/ptl/tcp/ptl_tcp.c b/src/mca/ptl/tcp/ptl_tcp.c
index 0c7b50d..af9c377 100644
--- a/src/mca/ptl/tcp/ptl_tcp.c
+++ b/src/mca/ptl/tcp/ptl_tcp.c
@@ -152,7 +152,7 @@ static pmix_status_t connect_to_peer(struct pmix_peer_t *peer,
     /* if I am a client, then we need to look for the appropriate
      * connection info in the environment */
     if (PMIX_PROC_IS_CLIENT(pmix_globals.mypeer)) {
-        if (NULL != (evar = getenv("PMIX_SERVER_URI3"))) {
+        if (NULL != (evar = getenv("PMIX_SERVER_URI4"))) {
             /* we are talking to a v3 server */
             pmix_client_globals.myserver->proc_type = PMIX_PROC_SERVER | PMIX_PROC_V3;
             pmix_output_verbose(2, pmix_ptl_base_framework.framework_output,
@@ -162,6 +162,16 @@ static pmix_status_t connect_to_peer(struct pmix_peer_t *peer,
             if (NULL == pmix_globals.mypeer->nptr->compat.bfrops) {
                 return PMIX_ERR_INIT;
             }
+        } else if (NULL != (evar = getenv("PMIX_SERVER_URI3"))) {
+            /* we are talking to a v3 server */
+            pmix_client_globals.myserver->proc_type = PMIX_PROC_SERVER | PMIX_PROC_V3;
+            pmix_output_verbose(2, pmix_ptl_base_framework.framework_output,
+                                "V3 SERVER DETECTED");
+            /* must use the v3 bfrops module */
+            pmix_globals.mypeer->nptr->compat.bfrops = pmix_bfrops_base_assign_module("v3");
+            if (NULL == pmix_globals.mypeer->nptr->compat.bfrops) {
+                return PMIX_ERR_INIT;
+            }
         } else if (NULL != (evar = getenv("PMIX_SERVER_URI21"))) {
             /* we are talking to a v2.1 server */
             pmix_client_globals.myserver->proc_type = PMIX_PROC_SERVER | PMIX_PROC_V21;
diff --git a/src/mca/ptl/tcp/ptl_tcp_component.c b/src/mca/ptl/tcp/ptl_tcp_component.c
index 02c20a0..27313f6 100644
--- a/src/mca/ptl/tcp/ptl_tcp_component.c
+++ b/src/mca/ptl/tcp/ptl_tcp_component.c
@@ -555,7 +555,7 @@ static pmix_status_t setup_listener(pmix_info_t info[], size_t ninfo,
     }

     lt = PMIX_NEW(pmix_listener_t);
-    lt->varname = strdup("PMIX_SERVER_URI3:PMIX_SERVER_URI2:PMIX_SERVER_URI21");
+    lt->varname = strdup("PMIX_SERVER_URI4:PMIX_SERVER_URI3:PMIX_SERVER_URI2:PMIX_SERVER_URI21");
     lt->protocol = PMIX_PROTOCOL_V2;
     lt->ptl = (struct pmix_ptl_module_t*)&pmix_ptl_tcp_module;
     lt->cbfunc = connection_handler;
```
</details>

**Comment by rhc54** [comment]
Looks reasonable to me - why don't you add that patch to this PR and commit it?

**Comment by karasevb** [comment]
Ready to go, double check showed that all cross-version tests are passed with the last commit.

**Comment by jjhursey** [comment]
@karasevb Thanks for chasing down that cross version issue. I'll work on a CI tester for cross-version issues (it's been on my to do list for a while now) so hopefully, those types of things don't sneak in in the future.

**Pull request merged**
