### PR TITLE
v3.0/dstore: adds new `ds21` component with new locking scheme

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #786

### CODE REVIEW

**Comment by karasevb** [comment]
@gpaulsen @jjhursey

**Comment by rhc54** [comment]
@karasevb Can you please resolve the conflicts?

**Comment by jjhursey** [comment]
@karasevb This PR also has a merge conflict (likely the same one that you resolved in PR #815

**Comment by karasevb** [comment]
Ready to go.

**Comment by artpol84** [comment]
@rhc54 @jjhursey do we plan to merge this?

**Pull request merged**
