### PR TITLE
dstore: adds new `ds21` component with new locking scheme

### PR DESCRIPTION
**Pull request by karasevb**
This PR is in progress, do not merge. 
The current state of PR works only for one node and can be tested with explicitly define dstore component (`ds12` either `ds21`): 
```sh
export PMIX_MCA_gds=ds21,hash
./run_cmd.sh
```

Refs #665

### CODE REVIEW

**Comment by karasevb** [comment]
@gpaulsen

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ad001662501c42bc22a4c960e44555e4

**Comment by gpaulsen** [comment]
This is great progress!  If this can be dev complete by end of the week, it will make Open MPI v4.0, which would be a big win for Open MPI.  After Friday, there will be about 1 month of bug fixing time before RC1 for Open MPI v4.0

@hppritcha this may be a desirable performance improvement for Open MPI v4.0 if it can be ready in time.

**Comment by rhc54** [comment]
Errr...hold on there, ace. This is going into PMIx master. We just released v3.0 of PMIx and don't have another release even scheduled yet. So there is no way in the world this makes it into OMPI by Friday.

**Comment by rhc54** [comment]
And to be clear: this has zero impact on OMPI itself. I understand that it helps with the PAMI problem, but that is a completely different issue.

**Comment by jladd-mlnx** [comment]
bot:mellanox:retest

**Comment by gpaulsen** [comment]
@rhc54 Oh Sorry, you're right.  I got confused.  (too many contexts are ruining my brain)

The delivery mechanism for this is a new feature release of PMIx, and possibly a backport to a new feature release on PMIx v2.3?  Is that the current thought?

**Comment by rhc54** [comment]
I believe we agreed it could go into v2.2 and v3.1 as a new component that doesn't change the API but is more than a bug fix. We just don't have a date for when those might happen (probably before SC?)

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/fb2979b12f315b26d1b4db98726200a0

**Comment by karasevb** [comment]
New locking scheme is available for testing. 
The updated set of commits fixes known issues, but currently, it works only for a single namespace.
I'm working for support multi-namespace mode.

**Comment by jladd-mlnx** [comment]
@gpaulsen this is ready for IBM to test.

**Comment by jjhursey** [comment]
@karasevb Do you know why the Mellanox and IBM/XL CI tests are failing? They both seem to be build system related, but in two different locations.

**Comment by jladd-mlnx** [comment]
I'm pretty sure it's because of https://github.com/open-mpi/ompi/pull/5414#issuecomment-405777423

**Comment by rhc54** [comment]
It cannot be due to a change in OMPI - this is PMIx and we don't even build OMPI in the tests. The reason for the IBM failure is simply that a file is being left out of the tarball:
```
make[3]: Entering directory `/var/lib/jenkins/jobs/gh-pmix-pr/workspace/src/mca/gds/ds12'
06:54:27 make[3]: *** No rule to make target `ds21_lock.h', needed by `distdir'.  Stop.
06:54:27 make[3]: Leaving directory `/var/lib/jenkins/jobs/gh-pmix-pr/workspace/src/mca/gds/ds12'
06:54:27 make[2]: *** [distdir] Error 1
06:54:27 make[2]: Leaving directory `/var/lib/jenkins/jobs/gh-pmix-pr/workspace/src'
06:54:27 make[1]: *** [distdir] Error 1
06:54:27 make[1]: Leaving directory `/var/lib/jenkins/jobs/gh-pmix-pr/workspace'
06:54:27 make: *** [dist] Error 2
06:54:
```

I haven't looked at the Mellanox failure yet, but it is likely something similar.

**Comment by karasevb** [comment]
```
16:54:27  (cd mca/gds/ds12 && make  top_distdir=../../../../pmix-4.0.0 distdir=../../../../pmix-4.0.0/src/mca/gds/ds12 \
16:54:27      am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
16:54:27 make[3]: Entering directory `/var/lib/jenkins/jobs/gh-pmix-pr/workspace/src/mca/gds/ds12'
16:54:27 make[3]: *** No rule to make target `ds21_lock.h', needed by `distdir'.  Stop.
```

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f6c3917cba7d291999a849160cc027d1

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by karasevb** [comment]
bot:ibm:retest

**Comment by karasevb** [comment]
Here the results of 4 nodes (28ppn): 
image
Details of the measurements:
image

**Comment by karasevb** [comment]
@jladd-mlnx @artpol84

**Comment by karasevb** [comment]
@gpaulsen @jjhursey all known issues are resolved, ready for full testing.

**Comment by jladd-mlnx** [comment]
Nice work @karasevb @artpol84 !!

**Comment by jjhursey** [comment]
@karasevb Thanks! I'll test it out early next week (Mon or Tues).

Are there any cross version concerns with this? So if the server is running a version before this change, but the client is running this change (and vice versa) will that work correctly?

**Comment by gpaulsen** [comment]
Thanks for the hard work.  Looking forward to hearing the results of testing.

**Comment by karasevb** [comment]
@jjhursey compatibility should be saved for both directions, I have tested this PR thru `./pmix_test -e ...` against v2.1 and vice versa, it works well. The issue was in modules assignment, that has been fixed in the latest commit.

**Comment by rhc54** [comment]
@karasevb Just a reminder (as I know I tend to forget as well). When testing across versions, you need to configure with ```--enable-static --disable-shared``` to ensure that the child processes aren't using the server's plugins. Otherwise, the test can yield false results.

IIRC, IBM proposed this to go back to the PMIx v2.x series - which means it would appear as a new PMIx v2.2.x series. Doing so necessitates a much more expanded test regime, I'm afraid, as it means we also have to add it to the v3.x series (would have to be a v3.1 series). This creates a rather strange break as it would be in v2.2, not in v3.0, and then appear again in v3.1. However, since it is outside the user's view, I suspect we can deal with it.

If we go forward with that plan, then you'll need to test/verify the following combinations:

- [ ] master as server, with new plugin
    - [ ] v3.0.0 client without plugin
    - [ ] v3.0.0 client with plugin (v3.1.0)
    - [ ] v2.1.3 client without plugin
    - [ ] v2.1.3 client with plugin (v2.2.0)
    - [ ] v1.2.5 client

- [ ] master as server, without new plugin
    - [ ] v3.0.0 client with plugin (v3.1.0)
    - [ ] v2.1.3 client with plugin (v2.2.0)

- [ ] v3.0.0 as server, with new plugin
    - [ ] v3.0.0 client without plugin
    - [ ] v3.0.0 client with plugin (v3.1.0)
    - [ ] v2.1.3 client without plugin
    - [ ] v2.1.3 client with plugin (v2.2.0)
    - [ ] v1.2.5 client

- [ ] v3.0.0 as server, without new plugin
    - [ ] v3.0.0 client with plugin (v3.1.0)
    - [ ] v2.1.3 client with plugin (v2.2.0)

- [ ] v2.1.3 as server, with new plugin (v2.2.0)
    - [ ] v3.0.0 client without plugin
    - [ ] v3.0.0 client with plugin  (v3.1.0)
    - [ ] v2.1.3 client without plugin
    - [ ] v1.2.5 client

- [ ] v2.1.3 as server, without new plugin
    - [ ] v3.0.0 client with plugin (v3.1.0)
    - [ ] v2.1.3 client with plugin (v2.2.0)

The reason we need such coverage is that we are backporting to an existing release series and so we will encounter a much broader range of scenarios. Thus, the selection logic becomes a concern. An alternative is to only offer the new plugin going forward - in that case, just the tests where master is the server with the new plugin would be required.

**Comment by karasevb** [comment]
Synced with `master`

**Comment by jjhursey** [comment]
Let's discuss the backwards/cross-version compatibility on the PMIx call this week. I'm worried that backporting it to the v2.x series is going to be a cross-version testing nightmare. it's possible that IBM roll's their own v2.x series with this change and a noted restriction on cross-version compatibility (basically that it's not fully tested/supported). However, if we can stay inline with the community release that would be preferable. I should have some testing done by Thursday on this branch, so I can report that too.

**Comment by jjhursey** [comment]
I tested this tonight on two Power9 machines running 160 PPN each (larger machines are booked right now). I used a benchmark that emulates what our expected load is on the `PMIx_Get` (since Boris already posted the pmix_bench results earlier). Below is a summary:
```
2,403 concurrent PMIx_Get calls from each process.
PMIX_MCA_gds=ds12,hash  529 usec per PMIx_Get call average
PMIX_MCA_gds=ds21,hash   45 usec per PMIx_Get call average
--
13,283 concurrent PMIx_Get calls from each process. (inflated beyond expected)
PMIX_MCA_gds=ds12,hash  608 usec per PMIx_Get call average
PMIX_MCA_gds=ds21,hash   55 usec per PMIx_Get call average
```
So the new dstore (`ds21`) takes about 1/10 the time of the previous component. That's pretty great!

**Comment by rhc54** [comment]
I'm okay with it going into master, but as I said, we cannot move it to the release branches without verifying cross-version compatibility.

**Comment by jjhursey** [comment]
@karasevb Thanks for those links. I'll try out those branches too. I'm fine with the small commit's if it makes things easier.

Let's bring this into master, and discuss on Thursday about the cross version dimension. @artpol84 can you do the formal review of this PR and give it a 👍 ?

**Comment by artpol84** [comment]
Should be good to go

**Comment by artpol84** [comment]
I may not be able to make it on the call today as im traveling.
If I won’t be there I’m good with either discussing it on the next call or having a dedicated call earlier next week

**Comment by rhc54** [comment]
Give all the time differences, let's move ahead with this one and fix Josh's.

**Comment by jjhursey** [comment]
On the call today we discussed the cross version dimension of this PR, and cross version support in general. We don't know definitively whether or not this new component will cause a break. Probably not, but we need a test to check.

So the first step is to assess where we are at. I'm going to put together a script that tests the cross version support, and post the results either to the mailing list or as an issue (if I use an issue I'll let everyone know). If the test comes back clean, then we should be fine. If there is a break then we will probably need to discuss further.

I'm hoping to have that script ready by the end of the week or early next week.

**Comment by jjhursey** [comment]
@rhc54 I put together the script, and it works by building and running. But it doesn't validate the output, which seems to have some failures. The server passes, so the test passes. But it looks like errors on the client side.

First cut of the script:
 * https://gist.github.com/jjhursey/9e3d51e5ee88362d906556e3eb7cc7ec

Output:
 * https://gist.github.com/jjhursey/dae4403bec5bd0f7e081aaa238c19bac

I'm out of the office for the next week. But I wanted to post my progress on this in case other can pick it up while I'm out.

**Comment by gpaulsen** [comment]
@karasevb would it be possible for you to create a v2.x pull request of 2.x_dstore/lock this week?
Even though this PR has not yet been merged to PMIx master?  This would allow us (IBM/SMPI) to do some internal testing of this PR against our v2.x based PMIx (not using the PMIx cross-version support for our PMIx dstore testing)?

**Comment by jjhursey** [comment]
I don't know if those branches need to be re-synch'ed with the upstream branches. But having the PRs ready would be very helpful.

I'm hoping to have cycles to look into the state of cross-version later this week or next. I suspect that there is not additional issues introduced by this PR, but we wanted to confirm before accepting this change in the v3 and v2 series.

**Comment by karasevb** [comment]
@gpaulsen @jjhursey 
This week I synchronize the target branches.

**Comment by jjhursey** [comment]
@karasevb I'm using your 2.x porting branch from a few days ago. I'm seeing a crash on the server side during connection establishment with this signature:
```
#8  0x00002000004d6a3c in __strlen_power8 () from /lib64/libc.so.6
#9  0x00002000024137f4 in connection_handler () from /gpfs/alpinetds/ven201/scratch/jjhursey/local/smpi/current/lib/pmix/mca_ptl_usock.so
#10 0x00002000002c2b10 in event_process_active_single_queue (activeq=0x212e9380, base=0x2137f8f0) at event.c:1368
#11 event_process_active (base=<optimized out>) at event.c:1438
#12 event_base_loop (base=0x2137f8f0, flags=<optimized out>) at event.c:1642
#13 0x00002000001d6bac in progress_engine () from /gpfs/alpinetds/ven201/scratch/jjhursey/local/smpi/current/lib/libpmix.so.2
#14 0x0000200000388af4 in start_thread () from /lib64/libpthread.so.0
#15 0x0000200000548814 in clone () from /lib64/libc.so.6
```

It's a:
```
 Signal: Segmentation fault (11)
 Failing at address: 0x138
```

I was running 168 PPN across 1024 nodes at the time. I've also seen this happen at 100 PPN, though less frequently. Bellow 100 PPN I have not seen this error (yet anyway).

Now this could be something fixed in the branch since you last synchronized, so I can retry once you have a new branch for me to try. Or it could be bug we need to track down.

It's difficult for me to test with `master` or I would have. It's much easier for me to test with the 2.x branch, which is why I was using your ported branch. Let me know when it's updated. Thanks!

**Comment by jjhursey** [comment]
I donno. We shouldn't be forcing any envars.
I did a quick check, and using that branch I see this envar:
`PMIX_PTL_MODULE=tcp,usock`
So it's coming up as an option. Should I force it to be just `tcp`?

**Comment by rhc54** [comment]
That is okay and correct - what I don't understand is why the client is telling the server to use usock. It sounds like the client/server component selection is getting confused.

**Comment by artpol84** [comment]
@jjhursey what is the status of this?

**Pull request merged**
