### PR TITLE
v1.2/test: eliminated the usage of through ranking for namespaces

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to 83b3d0dccd932a3bf40adf11df87d5e1cf4c9abf

### CODE REVIEW

**Comment by karasevb** [comment]
Refs https://github.com/pmix/pmix/issues/1259

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/49462f249e7fa0cca579dcbc404e57bb

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/acc6e03397ab227781ac652621c17064

**Comment by karasevb** [comment]
Mellanox Jenkins will be updated.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f077c0fa94141810cdaa6bb9428840b6

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/8789011c56d5b280e9c62e186bf35e6a

**Comment by artpol84** [comment]
bot:mellanox:retest

**Pull request merged**
