### PR TITLE
Update the configury to resolve problems with automake 1.13.

### PR DESCRIPTION
**Pull request by rhc54**
Refs https://github.com/open-mpi/ompi/issues/4109

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
@rhc54 Just wanted to confirm - this fixes OMPI Issue https://github.com/open-mpi/ompi/issues/4109 ? It looks like it will, but have not tested with that blend of autotools.

**Comment by rhc54** [comment]
I haven't tested it either - I can create a PR for OMPI based on this one, though, and ask them to test it over there.

**Comment by rhc54** [comment]
See https://github.com/open-mpi/ompi/pull/4147

**Comment by jjhursey** [comment]
Is PR #503 a proper fix for this?

**Comment by rhc54** [comment]
I think/hope so - will update this PR shortly

**Comment by rhc54** [comment]
Okay, found remaining AC_PROG_CC and remove it - checked with AM 1.13.4. Good to go.

**Comment by jjhursey** [comment]
Open MPI found this problem, so a couple links to the discussion there:
 * OMPI v2.1.2 took part of this PR https://github.com/open-mpi/ompi/pull/4196
 * OMPI v2.1.3 will include the whole update from PMIx in https://github.com/open-mpi/ompi/pull/4147

**Comment by rhc54** [comment]
Yep, good to go...

**Pull request merged**
