### PR TITLE
test: fixed the client rank determine for testing under SLURM

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>
(cherry picked from commit eb44c18493a66d4459d8d7e89a3f26adacf7261d)

### CODE REVIEW

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
@rhc54 Indeed we need to fix it. Will do.
@Di0gen can you please fix it as for OMPI?

**Comment by Di0gen** [comment]
bot:retest

**Comment by artpol84** [comment]
@Di0gen thanks!
@rhc54 should be fixed now.

**Comment by rhc54** [comment]
Thank you!!

**Pull request merged**
