### PR TITLE
Backport support for libev

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey This technically isn't required for v3.1.4, but @jdinan could really use it. Let me know what you think about the backport.

**Comment by rhc54** [comment]
@jdinan Could you or someone on your team give this a test run?

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/42a96c1cd17288bcb16f298bb9ad27c5

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/c2af2bc12635d3307c504fa01a1bbda9

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b11f2aa2f052bd1917157dd2314e45b5

**Comment by rhc54** [comment]
bot:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/e23577133c7706de88c0b126f2e6e624

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/43b8f9ce1c41874de4369581d29bbfda

**Comment by rhc54** [comment]
@jjhursey Could you please take a look at the xversion tester? I'm not seeing any build failures, even on your Jenkins servers, yet the xversion tester is failing to build this PR.

**Comment by rhc54** [comment]
bot:mellanox:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/61eb45590ff4ca41f5d710a2ddfc4cdb

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0d66a18be73918e94004f21de988b9aa

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/a4b230fb2af90773f1717dc3edaea508

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/7e74d8ca85a327e1c27cdc45548b38de

**Comment by jdinan** [comment]
Tests are running.  Should have results in a couple hours.  Thanks!

**Comment by jdinan** [comment]
I'm seeing a build error in Travis with this branch:
```
git clone -b cmr31/ev --depth 10 https://github.com/rhc54/pmix-master.git pmix
cd pmix
./autogen.pl
./configure --prefix=$TRAVIS_INSTALL/pmix --with-platform=optimized --with-libev
make install
```
```
PMIx configuration:
-----------------------
Version: 3.1.4rc1
Debug build: no
Platform file: ./contrib/platform/optimized
External Packages
-----------------------
HWLOC: yes (/usr/include)
libev:
 
Making install in config
make[1]: Entering directory '/home/travis/travis/src/pmix/config'
make[2]: Entering directory '/home/travis/travis/src/pmix/config'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/travis/travis/src/pmix/config'
make[1]: Leaving directory '/home/travis/travis/src/pmix/config'
Making install in contrib
make[1]: Entering directory '/home/travis/travis/src/pmix/contrib'
make[2]: Entering directory '/home/travis/travis/src/pmix/contrib'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/travis/travis/install/pmix/share/pmix'
 /usr/bin/install -c -m 644 pmix-valgrind.supp '/home/travis/travis/install/pmix/share/pmix'
make[2]: Leaving directory '/home/travis/travis/src/pmix/contrib'
make[1]: Leaving directory '/home/travis/travis/src/pmix/contrib'
Making install in include
make[1]: Entering directory '/home/travis/travis/src/pmix/include'
make[2]: Entering directory '/home/travis/travis/src/pmix/include'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/travis/travis/install/pmix/include'
 /usr/bin/install -c -m 644 pmix.h pmix_server.h pmix_tool.h pmix_extend.h pmi.h pmi2.h '/home/travis/travis/install/pmix/include'
 /bin/mkdir -p '/home/travis/travis/install/pmix/include'
 /usr/bin/install -c -m 644 pmix_common.h pmix_version.h pmix_rename.h '/home/travis/travis/install/pmix/include'
make[2]: Leaving directory '/home/travis/travis/src/pmix/include'
make[1]: Leaving directory '/home/travis/travis/src/pmix/include'
Making install in src
make[1]: Entering directory '/home/travis/travis/src/pmix/src'
Making install in util/keyval
make[2]: Entering directory '/home/travis/travis/src/pmix/src/util/keyval'
  LEX      keyval_lex.c
  CC       keyval_lex.lo
keyval_lex.c: In function ‘yy_get_next_buffer’:
keyval_lex.c:1343:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                            ^
  CCLD     libpmixutilkeyval.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Entering directory '/home/travis/travis/src/pmix/src/util/keyval'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/travis/travis/src/pmix/src/util/keyval'
make[2]: Leaving directory '/home/travis/travis/src/pmix/src/util/keyval'
Making install in mca/base
make[2]: Entering directory '/home/travis/travis/src/pmix/src/mca/base'
  CC       pmix_mca_base_close.lo
  CC       pmix_mca_base_cmd_line.lo
  CC       pmix_mca_base_component_compare.lo
  CC       pmix_mca_base_component_find.lo
  CC       pmix_mca_base_component_repository.lo
  CC       pmix_mca_base_components_open.lo
  CC       pmix_mca_base_components_close.lo
  CC       pmix_mca_base_components_select.lo
  CC       pmix_mca_base_list.lo
  CC       pmix_mca_base_open.lo
  CC       pmix_mca_base_var.lo
  CC       pmix_mca_base_var_enum.lo
  CC       pmix_mca_base_var_group.lo
  CC       pmix_mca_base_parse_paramfile.lo
  CC       pmix_mca_base_components_register.lo
  CC       pmix_mca_base_framework.lo
  CCLD     libpmix_mca_base.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Entering directory '/home/travis/travis/src/pmix/src/mca/base'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/travis/travis/install/pmix/share/pmix'
 /usr/bin/install -c -m 644 help-pmix-mca-base.txt help-pmix-mca-var.txt '/home/travis/travis/install/pmix/share/pmix'
make[3]: Leaving directory '/home/travis/travis/src/pmix/src/mca/base'
make[2]: Leaving directory '/home/travis/travis/src/pmix/src/mca/base'
Making install in mca/common
make[2]: Entering directory '/home/travis/travis/src/pmix/src/mca/common'
make[3]: Entering directory '/home/travis/travis/src/pmix/src/mca/common'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/travis/travis/src/pmix/src/mca/common'
make[2]: Leaving directory '/home/travis/travis/src/pmix/src/mca/common'
Making install in mca/bfrops
make[2]: Entering directory '/home/travis/travis/src/pmix/src/mca/bfrops'
  CC       base/bfrop_base_frame.lo
  CC       base/bfrop_base_fns.lo
  CC       base/bfrop_base_select.lo
  CC       base/bfrop_base_copy.lo
  CC       base/bfrop_base_pack.lo
  CC       base/bfrop_base_print.lo
  CC       base/bfrop_base_unpack.lo
In file included from base/bfrop_base_unpack.c:27:0:
/home/travis/travis/src/pmix/src/include/types.h:272:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 PMIX_EXPORT int pmix_event_assign(struct event *ev, pmix_event_base_t *evbase,
             ^
/home/travis/travis/src/pmix/src/include/types.h:278:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 PMIX_EXPORT int pmix_event_add(struct event *ev, struct timeval *tv);
             ^
/home/travis/travis/src/pmix/src/include/types.h:279:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 PMIX_EXPORT int pmix_event_del(struct event *ev);
             ^
/home/travis/travis/src/pmix/src/include/types.h:280:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 PMIX_EXPORT void pmix_event_active (struct event *ev, int res, short ncalls);
             ^
/home/travis/travis/src/pmix/src/include/types.h:281:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 PMIX_EXPORT void pmix_event_base_loopexit (pmix_event_base_t *b);
             ^
/home/travis/travis/src/pmix/src/include/types.h:289:1: error: unknown type name ‘PMIX_EXPORT’
 PMIX_EXPORT pmix_event_t* pmix_event_new(pmix_event_base_t *b, int fd,
 ^
/home/travis/travis/src/pmix/src/include/types.h:289:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 PMIX_EXPORT pmix_event_t* pmix_event_new(pmix_event_base_t *b, int fd,
                         ^
In file included from /home/travis/travis/src/pmix/src/include/pmix_globals.h:39:0,
                 from base/bfrop_base_unpack.c:32:
/home/travis/travis/src/pmix/src/class/pmix_hotel.h: In function ‘pmix_hotel_checkin’:
/home/travis/travis/src/pmix/src/class/pmix_hotel.h:204:9: error: implicit declaration of function ‘pmix_event_add’ [-Werror=implicit-function-declaration]
         pmix_event_add(&(room->eviction_timer_event),
         ^
/home/travis/travis/src/pmix/src/class/pmix_hotel.h: In function ‘pmix_hotel_checkout’:
/home/travis/travis/src/pmix/src/class/pmix_hotel.h:264:13: error: implicit declaration of function ‘pmix_event_del’ [-Werror=implicit-function-declaration]
             pmix_event_del(&(room->eviction_timer_event));
             ^
cc1: some warnings being treated as errors
Makefile:719: recipe for target 'base/bfrop_base_unpack.lo' failed
make[2]: *** [base/bfrop_base_unpack.lo] Error 1
make[2]: Leaving directory '/home/travis/travis/src/pmix/src/mca/bfrops'
Makefile:1852: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/travis/travis/src/pmix/src'
Makefile:742: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by jdinan** [comment]
I'm not sure if you will be able to view it, but the complete log is here: https://travis-ci.org/jdinan/sandia-shmem/jobs/561052369

**Comment by rhc54** [comment]
Interesting - love the differences we see from different environments. I added a header that should resolve the problem. @jdinan Can you please give it another shot?

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
Grrr...one more CI that is failing for infrastructure reasons, so try again:

bot:ibm:xvercheck:retest

**Comment by jjhursey** [comment]
Yeah, I need to adjust the build script so that the xver tests dump a proper report when they hit a build issue. I'll see if I can't sort that out this weekend.

**Comment by jdinan** [comment]
@rhc54 Looks good on my end -- thanks!

**Pull request merged**
