### PR TITLE
CI Test PR - xversion

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
Working on a CI test for cross-version support:
 * Docker repo: https://github.com/jjhursey/pmix-xver-tester
 * Docker Hub: https://cloud.docker.com/u/jjhursey/repository/docker/jjhursey/pmix-xver-tester

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/032a6820b569b94e255daa05fc4b037f

**Comment by jjhursey** [comment]
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Ok. I think this branch served its purpose. Closing now that the Cross-version test is running live.

**Pull request closed without merging**
