### PR TITLE
Update v3.1 with all relevant commits from master

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
Only failures are in the Mellanox tests that are known to be broken at this time.

**Comment by artpol84** [comment]
@rhc54 the way I understood @jjhursey Mellanox jenkins wasn't broken but the repo was changed in some way that broke it. I think this is an important event that needs investigation rather than ignorance.
Also, it wasn't "known" to be broken (at least we didn't know that). I think it would be better in future if you can let us know before declaring it broken and ignoring.

**Comment by artpol84** [comment]
Ref. #929

**Comment by rhc54** [comment]
I think you misunderstood @jjhursey, or perhaps he was also misunderstanding things as he didn't have any code contributions. The fact is that Mellanox Jenkins was running, but the tests it was executing were "out-of-sync" with the repository tests. This was due to @karasevb and yourself working on the new multi-node feature.

I assume that you are monitoring the repo and paying attention when you look at your own PR to see that all PRs are failing, including your own. I wasn't particularly concerned as I would look into the Mellanox output, see the tests that were failing, and then verified that the cmd line options couldn't possibly work with the tests as-is in the repo. Since you guys were busy working on those in a separate PR, it was easy enough to just ensure the rest of the tests were passing.

**Pull request merged**
