### PR TITLE
dstore: Introduce session supports

### PR DESCRIPTION
**Pull request by karasevb**
defined the key name to set session id
Corresponds the PR #268

Signed-off-by: Boris Karasev <karasev.b@gmail.com>

### CODE REVIEW

**Comment by jjhursey** [comment]
@karasevb Is this needed for `v1.2.1`? Who should review?

**Comment by artpol84** [comment]
@jjhursey this is a stub to address https://github.com/open-mpi/ompi/issues/2737 in the future when/if session ID support will be implemented in OMPI by @rhc54 or us.
I'd like to know @rhc54 opinion.

**Comment by jjhursey** [comment]
Per discussion on the teleconf today: We are pushing this off to v1.2.2

**Comment by artpol84** [comment]
This can be closed.

**Pull request closed without merging**
