### PR TITLE
Update to full v3.1

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@artpol84 @karasevb Can you please take a glance at these failures and provide some idea of the source? I updated your tests here to match what is in master - is it just a mismatch between the tests Jenkins is expecting vs the updated tests?

**Comment by artpol84** [comment]
@rhc54 I'll take a look tomorrow (traveling now)

**Comment by artpol84** [comment]
@karasevb should have fixed that now

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
bot:mellanox:retest

**Comment by rhc54** [comment]
Thanks @artpol84 @karasevb !

**Pull request merged**
