### PR TITLE
Update simple tests to use job size instead of universe, fix Log code path

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/db315f9d5d362ba7f0d9870df8ec6075

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dc07f5702e0c55a6e35b560053286c25

**Comment by rhc54** [comment]
Sigh...build of the older versions somehow failed this time.

bot:ibm:xver:retest

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
Sigh...more infrastructure failures!

bot:ibm:xvercheck:retest

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
I surrender - can't get thru the IBM-to-GitHub issues.

**Pull request merged**
