### PR TITLE
v3.x/modex: optimization of rank identification size reduction

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to https://github.com/pmix/pmix/pull/1125

### CODE REVIEW

**Comment by jjhursey** [comment]
Ref issue #1169

**Comment by artpol84** [comment]
@rhc54 @jjhursey are we good to go?

**Comment by jjhursey** [comment]
I'd like to bring this in when all four of https://github.com/pmix/pmix/issues/1169 are ready. it looks like PR #1176 was still under work.

We are preparing a 3.1.3 so we want to coordinate with that since, if we take all 4 together, this will be merged for a 3.2 release series. Let's be sure to talk about it on Thursday's call.

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: Tool) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b33716948d777b17e7a7bd030da80d22

**Comment by rhc54** [comment]
@karasevb @artpol84 Please retarget v3.2 branch

**Comment by karasevb** [comment]
Replaced by #1403

**Pull request closed without merging**
