### PR TITLE
Fix the common framework integration

### PR DESCRIPTION
**Pull request by rhc54**
Common component libraries must be versioned.

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/dade0c3d69c7f2c9f1fbd0c3ca294d0d

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b890513ed2ccb9d191b6d18ef6460c2b

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/bfa48a3a2d1df7d783519a7316c81b5c

**Comment by ibm-ompi** [comment]
The IBM CI (GNU Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0d740dbe6f4aa713dc14ff026479acfa

**Comment by jjhursey** [comment]
@karasevb We will also need this picked into the v3.x and v2.x ports of the `ds21` component.

**Pull request merged**
