### PR TITLE
Check for EINVAL return from posix_fallocate

### LINKED ISSUE #1384: Use of posix_fallocate() is invalid on ZFS
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

PMIx version 3.1.3.

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Installation from source tarball downloaded from Github.

### Please describe the system on which you are running

OpenIndiana Hipster (illumos)

narval> uname -a
SunOS narval 5.11 illumos-6ccda740e0 i86pc i386 i86pc illumos

on Intel x86_64 (Dell PowerEdge T430).

-----------------------------

## Details of the problem

PMIx fails in the segment create code since pmix/src/mca/pshmem/mmap/pshmem_mmap.c uses posix_fallocate() which returns EINVAL on ZFS.

Either HAVE_POSIX_FALLOCATE should be undefined or EINVAL should be handled on ZFS.

Using posix_fallocate() would probably fail on other COW filesystems.

PMIx passes all the tests after deactivating the call to posix_fallocate() but another issue shows up after MPI_Finalize() in OpenMPI: failure to unlink temporary files for number of processes > 2.
For now I do not know if it is unrelated or a border effect; this will be reported in another issue or this ticket will be updated accordingly.

Kind regards,

Aurélien

### PR DESCRIPTION
**Pull request by rhc54**
Fixes #1384

Thanks to Aurelien Larcher for the report

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@alarcher Would you please give this a try and confirm it fixes the problem?

**Comment by ibm-ompi** [comment]
The IBM CI (Cross-version: make check) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/b0876b4e8b52e58afc6a25c74545165a

**Comment by ibm-ompi** [comment]
The IBM CI (XL Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by rhc54** [comment]
Infra error: can not access github. Looks like IBM is down.

@jjhursey Any ideas why?

**Comment by alarcher** [comment]
> @alarcher Would you please give this a try and confirm it fixes the problem?

Thank you, find below the test results:
```
PASS: run_tests00.pl
PASS: run_tests01.pl
PASS: run_tests02.pl
PASS: run_tests03.pl
PASS: run_tests04.pl
PASS: run_tests05.pl
PASS: run_tests06.pl
PASS: run_tests07.pl
PASS: run_tests08.pl
PASS: run_tests09.pl
PASS: run_tests10.pl
PASS: run_tests11.pl
PASS: run_tests12.pl
PASS: run_tests13.pl
PASS: run_tests14.pl
PASS: run_tests15.pl
============================================================================
Testsuite summary for pmix 3.1.3
============================================================================
# TOTAL: 16
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

```

**Comment by rhc54** [comment]
Excellent - many thanks!

**Comment by rhc54** [comment]
IBM infra problem again.

**Pull request merged**
