### PR TITLE
v2.x/dstore: adds new `ds21` component with new locking scheme

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to #786

### CODE REVIEW

**Comment by karasevb** [comment]
@gpaulsen @jjhursey

**Comment by rhc54** [comment]
We will need the conflict to be resolved, and could you please clarify that you tested the cross-version cases?

**Comment by jjhursey** [comment]
We haven't tested cross version support yet. I've asked some folks to take a look at that next week.

We can hold this PR until the Thursday meeting. Hopefully I'll have the cross version analysis by then.

**Comment by rhc54** [comment]
@karasevb Can you please resolve the conflicts?

**Comment by karasevb** [comment]
@rhc54 done

**Comment by nysal** [comment]
Some initial findings from the cross version testing - https://github.com/pmix/pmix/issues/877

**Comment by artpol84** [comment]
@rhc54 @jjhursey ping

**Pull request merged**
