### PR TITLE
test: Fix pmix_client/job-fence test checks

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
Address problems observed in #425

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/6cf256d180d0e8a256bb13c9243d0476

**Comment by artpol84** [comment]
ready for the merge.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/335042ea2a956adc23815f3840219446

**Comment by rhc54** [comment]
Probably should hold off until @jjhursey can resolve the PGI atomics issue

**Comment by artpol84** [comment]
Yes, definitely. Just prepared it for merhing

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d2ca5b8cfbee4fe3b5078553ce6e1cae

**Comment by jjhursey** [comment]
IBM PGI CI should be fixed now. bot:ibm:pgi:retest

**Pull request merged**
