### PR TITLE
dstore: fixed the logic of unmaping dstore segments

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@karasevb please, PR to the relevant release branches

**Comment by ggouaillardet** [comment]
fwiw, this fixes the PMIx test program

I did a quick check with PMIx `master` as an external PMIx for Open MPI, and a crash occur with a simple test.

At this stage, I cannot tell whether the root cause is PMIx or Open MPI

```
$ mpirun -np 1 hostname
c7
mpirun: ../../../../../../src/pmix/src/mca/gds/ds12/gds_dstore.c:2928: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
Aborted (core dumped)
```

**Comment by karasevb** [comment]
Will check

**Comment by ggouaillardet** [comment]
a similar/related (?) issue can be reproduced without Open MPI

```
./stability -n 1 -reps 1 -e /bin/true
```

that looks like a bozo case which is not correctly handled.

**Comment by karasevb** [comment]
@ggouaillardet Thanks!
The problem is clear, there is a dstor issue. I'm going to fix.

Could you clarify, `./stability -n 1 -reps 1 -e /bin/true` is reproduces the crash? I able to catch it only with `mpirun -np 1 hostname`.

**Comment by ggouaillardet** [comment]
yes, I confirm I do not need Open MPI to reproduce the issue

```
$ ./stability -n 1 -reps 1 -e /bin/true
Testing version 4.0.0
Running cycle 0
lt-stability: ../../../../../../src/pmix/src/mca/gds/ds12/gds_dstore.c:2928: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
Aborted (core dumped)
```

`dstore_del_nspace` is invoked by a PMIx thread, so there could be a race condition involved with `-reps 1`.

**Pull request merged**
