### PR TITLE
Fix node-local Fence detection

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54 @jjhursey I think this is what was causing the issues with the fence I mentioned on the call this week.

**Comment by rhc54** [comment]
@artpol84 Is this a problem in v3.1.x as well? Just wondering if this needs to go to the release branches given the detection issue (i.e., direct modex hid it).

**Comment by artpol84** [comment]
I will check.
I thought this local fence optimization only in master.

**Comment by artpol84** [comment]
I don't see the local tracker check in v3.1:
https://github.com/pmix/pmix/blob/v3.1/src/server/pmix_server_ops.c#L460

**Comment by rhc54** [comment]
ok, thanks for checking - just wanted to make sure we aren't missing something there.

**Pull request merged**
