### PR TITLE
test: Fix pmix_client/job-fence test checks

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>
(cherry picked from commit 9128350fc94ce8bf3ef0126433247c529e32518a)

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f752709c70ee21a53ea0c8dc3ff590ce

**Comment by artpol84** [comment]
@karasevb please review

**Comment by artpol84** [comment]
I've rebased the branch and squashed extra commit. So it's ready for the merge.

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/005fbb6bea497a325c77006b709e84a9

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/70217c44cedee264a304c74a85d3badb

**Comment by jjhursey** [comment]
IBM PGI CI should be fixed now. bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/4dfa0fd247465c8722508634efe447ad

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PGI Compiler) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/83bc3c285a8fc680d51ba59452c2a4f9

**Comment by rhc54** [comment]
bot:ibm:pgi:retest

**Comment by artpol84** [comment]
@rhc54 @jjhursey the master PR was merged. please consider this PR for merging.

**Pull request merged**
