### PR TITLE
dstor: rework dstor compatibility

### PR DESCRIPTION
**Pull request by karasevb**
Signed-off-by: Boris Karasev <karasev.b@gmail.com>

### CODE REVIEW

**Comment by karasevb** [comment]
@artpol84 please review

**Comment by artpol84** [comment]
much cleaner!
:+1:

**Comment by rhc54** [comment]
Question for you guys: I gather there are no changes required for v1.2 or v2.0, yes? So once you commit this to master, we cherry-pick it to v2.1 and we should be good?

**Comment by artpol84** [comment]
That is correct.

**Pull request merged**
